In [2]:
import pandas as pd

In [34]:
df = pd.read_csv("C:/Users/Mohammad Irfan/Downloads/dataset/epldata.csv")

In [16]:
df.head(10)

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3.0,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2.0,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2.0,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1.0,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2.0,France,0,4,1,1,0
5,Hector Bellerin,Arsenal,22,RB,3,30.0,1675,6.0,13.70%,119,2.0,Spain,0,2,1,1,0
6,Olivier Giroud,Arsenal,30,CF,1,22.0,2230,8.5,2.50%,116,2.0,France,0,4,1,1,0
7,Nacho Monreal,Arsenal,31,LB,3,13.0,555,5.5,4.70%,115,2.0,Spain,0,4,1,1,0
8,Shkodran Mustafi,Arsenal,25,CB,3,30.0,1877,5.5,4.00%,90,2.0,Germany,0,3,1,1,1
9,Alex Iwobi,Arsenal,21,LW,1,10.0,1812,5.5,1.00%,89,4.0,Nigeria,0,1,1,1,0

In [25]:
df1 = df.tail()

In [26]:
type(df)

pandas.core.frame.DataFrame

In [27]:
#I want to store last 5 records as test.csv
df1.to_csv("test.csv")

In [ ]:
!dir

In [29]:
pd.read_csv('test.csv')

,Unnamed: 0,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,456,Edimilson Fernandes,West+Ham,21,CM,2,5.0,288,4.5,0.40%,38,2.0,Switzerland,0,1,20,0,1
1,457,Arthur Masuaku,West+Ham,23,LB,3,7.0,199,4.5,0.20%,34,4.0,Congo DR,0,2,20,0,1
2,458,Sam Byram,West+Ham,23,RB,3,4.5,198,4.5,0.30%,29,1.0,England,0,2,20,0,0
3,459,Ashley Fletcher,West+Ham,21,CF,1,1.0,412,4.5,5.90%,16,1.0,England,0,1,20,0,1
4,460,Diafra Sakho,West+Ham,27,CF,1,10.0,214,5.5,0.10%,12,4.0,Senegal,0,3,20,0,0

In [ ]:
# In the above dataset we can see the 2nd column UNNAMED:0 which is a new column it has added.

In [46]:
# I have replaced all the commas with hashtag in my csv file. By default, it considers comma as the delimiter.
df = pd.read_csv("C:/Users/Mohammad Irfan/Downloads/dataset/epldata.csv", sep='#')

In [36]:
# I don't want to consider the first row as my header.
pd.read_csv("C:/Users/Mohammad Irfan/Downloads/dataset/epldata.csv", sep='#', header=None)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
1,Alexis Sanchez,Arsenal,28,LW,1,65,4329,12,17.10%,264,3,Chile,0,4,1,1,0
2,Mesut Ozil,Arsenal,28,AM,1,50,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
3,Petr Cech,Arsenal,35,GK,4,7,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
4,Theo Walcott,Arsenal,28,RW,1,20,2393,7.5,1.50%,122,1,England,0,4,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,Edimilson Fernandes,West+Ham,21,CM,2,5,288,4.5,0.40%,38,2,Switzerland,0,1,20,0,1
458,Arthur Masuaku,West+Ham,23,LB,3,7,199,4.5,0.20%,34,4,Congo DR,0,2,20,0,1
459,Sam Byram,West+Ham,23,RB,3,4.5,198,4.5,0.30%,29,1,England,0,2,20,0,0
460,Ashley Fletcher,West+Ham,21,CF,1,1,412,4.5,5.90%,16,1,England,0,1,20,0,1
461,Diafra Sakho,West+Ham,27,CF,1,10,214,5.5,0.10%,12,4,Senegal,0,3,20,0,0

In [37]:
# I want to give my own column names in the form of list.
pd.read_csv("C:/Users/Mohammad Irfan/Downloads/dataset/epldata.csv", sep='#', header=None, names=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q'])

,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q
0,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
1,Alexis Sanchez,Arsenal,28,LW,1,65,4329,12,17.10%,264,3,Chile,0,4,1,1,0
2,Mesut Ozil,Arsenal,28,AM,1,50,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
3,Petr Cech,Arsenal,35,GK,4,7,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
4,Theo Walcott,Arsenal,28,RW,1,20,2393,7.5,1.50%,122,1,England,0,4,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,Edimilson Fernandes,West+Ham,21,CM,2,5,288,4.5,0.40%,38,2,Switzerland,0,1,20,0,1
458,Arthur Masuaku,West+Ham,23,LB,3,7,199,4.5,0.20%,34,4,Congo DR,0,2,20,0,1
459,Sam Byram,West+Ham,23,RB,3,4.5,198,4.5,0.30%,29,1,England,0,2,20,0,0
460,Ashley Fletcher,West+Ham,21,CF,1,1,412,4.5,5.90%,16,1,England,0,1,20,0,1
461,Diafra Sakho,West+Ham,27,CF,1,10,214,5.5,0.10%,12,4,Senegal,0,3,20,0,0

In [38]:
# Skipping some rows like 2, 4, 460
pd.read_csv("C:/Users/Mohammad Irfan/Downloads/dataset/epldata.csv", sep='#', header=None, skiprows=[2,4,460])

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
1,Alexis Sanchez,Arsenal,28,LW,1,65,4329,12,17.10%,264,3,Chile,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
3,Laurent Koscielny,Arsenal,31,CB,3,22,912,6,0.70%,121,2,France,0,4,1,1,0
4,Hector Bellerin,Arsenal,22,RB,3,30,1675,6,13.70%,119,2,Spain,0,2,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
454,Pablo Zabaleta,West+Ham,32,RB,3,7,698,5,2.70%,45,3,Argentina,0,5,20,0,0
455,Edimilson Fernandes,West+Ham,21,CM,2,5,288,4.5,0.40%,38,2,Switzerland,0,1,20,0,1
456,Arthur Masuaku,West+Ham,23,LB,3,7,199,4.5,0.20%,34,4,Congo DR,0,2,20,0,1
457,Sam Byram,West+Ham,23,RB,3,4.5,198,4.5,0.30%,29,1,England,0,2,20,0,0
458,Diafra Sakho,West+Ham,27,CF,1,10,214,5.5,0.10%,12,4,Senegal,0,3,20,0,0

In [44]:
# Consider oe replace some values as null or NaN value by using na_values.
pd.read_csv("C:/Users/Mohammad Irfan/Downloads/dataset/epldata.csv", sep='#', header=None, na_values=['Arsenal','Mesut Ozil'])

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
1,Alexis Sanchez,NaN,28,LW,1,65,4329,12,17.10%,264,3,Chile,0,4,1,1,0
2,NaN,NaN,28,AM,1,50,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
3,Petr Cech,NaN,35,GK,4,7,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
4,Theo Walcott,NaN,28,RW,1,20,2393,7.5,1.50%,122,1,England,0,4,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,Edimilson Fernandes,West+Ham,21,CM,2,5,288,4.5,0.40%,38,2,Switzerland,0,1,20,0,1
458,Arthur Masuaku,West+Ham,23,LB,3,7,199,4.5,0.20%,34,4,Congo DR,0,2,20,0,1
459,Sam Byram,West+Ham,23,RB,3,4.5,198,4.5,0.30%,29,1,England,0,2,20,0,0
460,Ashley Fletcher,West+Ham,21,CF,1,1,412,4.5,5.90%,16,1,England,0,1,20,0,1
461,Diafra Sakho,West+Ham,27,CF,1,10,214,5.5,0.10%,12,4,Senegal,0,3,20,0,0

In [47]:
df.describe()   # gives descriptions about numerical data

,age,position_cat,market_value,page_views,fpl_value,fpl_points,region,new_foreign,age_cat,club_id,big_club,new_signing
count,461.000000,461.000000,461.000000,461.000000,461.000000,461.000000,460.000000,461.000000,461.000000,461.000000,461.000000,461.000000
mean,26.804772,2.180043,11.012039,763.776573,5.447939,57.314534,1.993478,0.034707,3.206074,10.334056,0.303688,0.145336
std,3.961892,1.000061,12.257403,931.805757,1.346695,53.113811,0.957689,0.183236,1.279795,5.726475,0.460349,0.352822
min,17.000000,1.000000,0.050000,3.000000,4.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000
25%,24.000000,1.000000,3.000000,220.000000,4.500000,5.000000,1.000000,0.000000,2.000000,6.000000,0.000000,0.000000
50%,27.000000,2.000000,7.000000,460.000000,5.000000,51.000000,2.000000,0.000000,3.000000,10.000000,0.000000,0.000000
75%,30.000000,3.000000,15.000000,896.000000,5.500000,94.000000,2.000000,0.000000,4.000000,15.000000,1.000000,0.000000
max,38.000000,4.000000,75.000000,7664.000000,12.500000,264.000000,4.000000,1.000000,6.000000,20.000000,1.000000,1.000000

In [49]:
df.dtypes

name             object
club             object
age               int64
position         object
position_cat      int64
market_value    float64
page_views        int64
fpl_value       float64
fpl_sel          object
fpl_points        int64
region          float64
nationality      object
new_foreign       int64
age_cat           int64
club_id           int64
big_club          int64
new_signing       int64
dtype: object

In [50]:
df

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3.0,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2.0,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2.0,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1.0,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2.0,France,0,4,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456,Edimilson Fernandes,West+Ham,21,CM,2,5.0,288,4.5,0.40%,38,2.0,Switzerland,0,1,20,0,1
457,Arthur Masuaku,West+Ham,23,LB,3,7.0,199,4.5,0.20%,34,4.0,Congo DR,0,2,20,0,1
458,Sam Byram,West+Ham,23,RB,3,4.5,198,4.5,0.30%,29,1.0,England,0,2,20,0,0
459,Ashley Fletcher,West+Ham,21,CF,1,1.0,412,4.5,5.90%,16,1.0,England,0,1,20,0,1
460,Diafra Sakho,West+Ham,27,CF,1,10.0,214,5.5,0.10%,12,4.0,Senegal,0,3,20,0,0

In [ ]:
#if we don't want the first column i.e. row indexes 0,1,2,3, so on. Then use index=False.
# or use header = False if you want to get rid of first row or header row.
# I want to use my own seperator instead of comma. So, define it using sep = *, %, etc.
# I want to store only 3 columns namely name, club, position & nationality.
df.to_csv("result.csv", index=False, header=False, sep="%", columns=['name','club','position','nationality'])

In [52]:
df.columns

Index(['name', 'club', 'age', 'position', 'position_cat', 'market_value',
       'page_views', 'fpl_value', 'fpl_sel', 'fpl_points', 'region',
       'nationality', 'new_foreign', 'age_cat', 'club_id', 'big_club',
       'new_signing'],
      dtype='object')

In [53]:
# I want club column.
df['club']

0       Arsenal
1       Arsenal
2       Arsenal
3       Arsenal
4       Arsenal
         ...
456    West+Ham
457    West+Ham
458    West+Ham
459    West+Ham
460    West+Ham
Name: club, Length: 461, dtype: object

In [54]:
# It has type = series
#There are 2 types of datatypes in pandas: Data frame and series.
#Series is a one single record, either be it row or column. Series is equivalent to a list. It is subset of data frame.
#Some of the API's will work for certain data-type and others may not.
type(df['club'])

pandas.core.series.Series

In [56]:
# I want to get the single column 'club' data which is series data type in form of DataFrame datatype. 
# We can achieve that by passing it as a list.
df[['club']]   # Now, type is data frame.

         club
0     Arsenal
1     Arsenal
2     Arsenal
3     Arsenal
4     Arsenal
..        ...
456  West+Ham
457  West+Ham
458  West+Ham
459  West+Ham
460  West+Ham

[461 rows x 1 columns]

In [57]:
type(df[['club']] )

pandas.core.frame.DataFrame

In [59]:
# If you want data of two columns then provide that in form of list otherwise it gives an error.
df[['club', 'nationality']]    # order doesn't matter

         club     nationality
0     Arsenal           Chile
1     Arsenal         Germany
2     Arsenal  Czech Republic
3     Arsenal         England
4     Arsenal          France
..        ...             ...
456  West+Ham     Switzerland
457  West+Ham        Congo DR
458  West+Ham         England
459  West+Ham         England
460  West+Ham         Senegal

[461 rows x 2 columns]

In [61]:
# Reading an excel file which has multiple pages within it. By default, it reads only the first page.
pd.read_excel("C:/Users/Mohammad Irfan/Downloads/LUSID Excel - Business Agility - Making Simple Changes Quickly & Easily.xlsx")

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,1) Create your Live Production Environment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,In LUSID you can segregate environments by mak...,NaN,NaN,NaN,NaN,NaN,LUSID API Knowledge Base: Scopes.,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,Each scope has a unique code which is used to ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,To manage your client's assets you will also n...,NaN,NaN,NaN,NaN,NaN,LUSID API Knowledge Base: Portfolios,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,A portfolio lives within a given scope. Each p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,"When you add a portfolio, you can specify whic...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,Scope:,Production-client,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,OK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,DisplayName,Description,Code,Created,BaseCurrency,CorporateActionSourceId,AccountingMethod,SubHoldingKeys,Result,NaN
26,NaN,NaN,NaN,1.0,Pension-fund,Pension fund for new client,Pension-fund,2019-09-08 11:49:22.720000,GBP,NaN,AverageCost,NaN,Error creating portfolio with id Pension-fund ...,NaN
27,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
pd.read_excel("C:/Users/Mohammad Irfan/Downloads/LUSID Excel - Business Agility - Making Simple Changes Quickly & Easily.xlsx", sheet_name='Add your take on balances')

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,3) Add your Take on Balances,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,Now that you have populated your instrument un...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,The official transfer took place 2 days ago. Y...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,For further usage of the set holdings API call...,NaN,NaN,NaN,NaN,NaN,LUSID API Docs: Set Holdings,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,Specify details of your holdings and add these...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,Scope:,Production-client,"To view a list of existing scopes, please s...",NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,Portfolio code:,Pension-fund,"To view a list of existing Portfolios, plea...",NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,Effective date:,2019-09-08 11:49:22.720000,The effective date refers to the date the h...,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,Mandatory fields,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,Instrument Id Types,Instrument Ids,Units,Cost,Currency,Portfolio Cost,Price,Purchase date,Settlement date
31,NaN,NaN,NaN,1.0,Figi,BBG000BF6B57,1050200,9147242,GBP,9147242,8.71,NaN,NaN
32,NaN,NaN,NaN,2.0,Figi,BBG006N6HZM7,100674,13085203.824,GBP,13085203.824,129.976,NaN,NaN
33,NaN,NaN,NaN,3.0,Figi,BBG0088JSC32,220456,23461147.976,GBP,23461147.976,106.421,NaN,NaN
34,NaN,NaN,NaN,4.0,Figi,BBG0000D14P3,97658,13522312.628,GBP,13522312.628,138.466,NaN,NaN
35,NaN,NaN,NaN,5.0,Figi,BBG001KKJLR4,320568,34677443.4,GBP,34677443.4,108.175,NaN,NaN
36,NaN,NaN,NaN,6.0,Figi,BBG000BKH1W6,2879200,6892804.8,GBP,6892804.8,2.394,NaN,NaN
37,NaN,NaN,NaN,7.0,Figi,BBG0065YWM39,4789100,28629239.8,GBP,28629239.8,5.978,NaN,NaN
38,NaN,NaN,NaN,8.0,Figi,BBG000D03XD4,6134800,101684310,GBP,101684310,16.575,NaN,NaN
39,NaN,NaN,NaN,9.0,Figi,BBG000BF46Y8,13456500,26058512.25,GBP,26058512.25,1.9365,NaN,NaN
40,NaN,NaN,NaN,10.0,Figi,BBG000BRVH05,8954300,40912196.7,GBP,40912196.7,4.569,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,Holdings set for portfolio code Pension-fund,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
# read data from html. I have multiple tables in the given url, so it will read all the tables and store all tables inside a list.

df2 = pd.read_html("https://www.basketball-reference.com/players/i/ibakase01.html?utm_source=direct&utm_medium=Share&utm_campaign=ShareTool")

In [68]:
# It's a list and has multiple DataFrames, so first extract a DataFrame and then see or export to a file.
type(df2)

list

In [69]:
# There are total 6 number of tables.
len(df2)

6

In [70]:
df2[0]

,Season,Age,Tm,Lg,Pos,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,2008-09,19.0,Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),...,Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain)
1,2009-10,20.0,OKC,NBA,PF,73,0,18.1,2.8,5.1,...,.630,1.9,3.5,5.4,0.1,0.3,1.3,0.9,2.7,6.3
2,2010-11,21.0,OKC,NBA,PF,82,44,27.0,4.1,7.5,...,.750,2.6,5.0,7.6,0.3,0.4,2.4,0.9,3.3,9.9
3,2011-12,22.0,OKC,NBA,PF,66,66,27.2,4.0,7.4,...,.661,2.9,4.6,7.5,0.4,0.5,3.7,1.2,2.7,9.1
4,2012-13,23.0,OKC,NBA,PF,80,80,31.1,5.6,9.7,...,.749,2.8,4.9,7.7,0.5,0.4,3.0,1.6,2.7,13.2
5,2013-14,24.0,OKC,NBA,PF,81,81,32.9,6.5,12.1,...,.784,2.8,6.0,8.8,1.0,0.5,2.7,1.5,2.9,15.1
6,2014-15,25.0,OKC,NBA,PF,64,64,33.1,5.8,12.3,...,.836,2.1,5.7,7.8,0.9,0.5,2.4,1.5,3.0,14.3
7,2015-16,26.0,OKC,NBA,PF,78,78,32.1,5.3,11.1,...,.752,1.8,5.0,6.8,0.8,0.5,1.9,1.4,2.7,12.6
8,2016-17,27.0,TOT,NBA,PF,79,79,30.7,6.0,12.4,...,.856,1.6,5.2,6.8,0.9,0.5,1.6,1.3,2.7,14.8
9,2016-17,27.0,ORL,NBA,PF,56,56,30.5,6.1,12.6,...,.846,1.8,5.0,6.8,1.1,0.6,1.6,1.2,2.5,15.1
10,2016-17,27.0,TOR,NBA,PF,23,23,31.0,5.6,12.1,...,.882,1.3,5.5,6.8,0.7,0.3,1.4,1.7,3.3,14.2
11,2017-18,28.0,TOR,NBA,PF,76,76,27.5,5.0,10.3,...,.797,1.0,5.3,6.3,0.8,0.4,1.3,1.2,2.8,12.6
12,2018-19,29.0,TOR,NBA,C,74,51,27.2,6.3,11.9,...,.763,2.1,6.0,8.1,1.3,0.4,1.4,1.5,2.9,15.0
13,2019-20,30.0,TOR,NBA,C,55,27,27.0,6.2,12.2,...,.718,2.1,6.1,8.2,1.4,0.5,0.8,2.0,2.8,15.4
14,2020-21,31.0,LAC,NBA,C,41,39,23.3,4.5,8.9,...,.811,1.8,4.9,6.7,1.8,0.2,1.1,1.1,1.9,11.1
15,2021-22,32.0,TOT,NBA,"C,PF",54,12,16.2,2.7,5.5,...,.727,1.1,3.5,4.6,0.9,0.2,0.6,0.8,1.9,6.8
16,2021-22,32.0,LAC,NBA,C,35,10,15.4,2.7,5.5,...,.690,1.1,3.1,4.3,1.0,0.2,0.7,0.9,1.6,6.6
17,2021-22,32.0,MIL,NBA,PF,19,2,17.8,2.8,5.5,...,.800,1.2,4.1,5.3,0.7,0.2,0.4,0.5,2.4,7.0
18,Career,NaN,NaN,NBA,NaN,903,697,27.6,5.0,9.8,...,.758,2.1,5.1,7.2,0.8,0.4,1.9,1.3,2.7,12.1
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,7 seasons,NaN,OKC,NBA,NaN,524,413,28.8,4.9,9.3,...,.745,2.4,5.0,7.4,0.6,0.4,2.5,1.3,2.8,11.6
21,4 seasons,NaN,TOR,NBA,NaN,228,177,27.6,5.8,11.4,...,.768,1.7,5.7,7.4,1.1,0.4,1.2,1.5,2.8,14.2
22,2 seasons,NaN,LAC,NBA,NaN,76,49,19.6,3.7,7.3,...,.768,1.5,4.1,5.6,1.4,0.2,1.0,1.0,1.7,9.0
23,1 season,NaN,ORL,NBA,NaN,56,56,30.5,6.1,12.6,...,.846,1.8,5.0,6.8,1.1,0.6,1.6,1.2,2.5,15.1
24,1 season,NaN,MIL,NBA,NaN,19,2,17.8,2.8,5.5,...,.800,1.2,4.1,5.3,0.7,0.2,0.4,0.5,2.4,7.0

In [72]:
# Saving to a excel csv file.
df2[5].to_csv("basketball_Data.csv")

In [73]:
pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [95]:
s = '''{
"name" : "mohd irfan",
"job" : "fresher",
"phone_no" : 93433953,
"comp" : ["tcs", "wipro", "microsoft", "google", "amazon"]
}
'''
# can validate your dataset in any json viewer online.

In [96]:
# json stands for JAVA script object notation
import json

In [97]:
s1 = json.loads(s)

I want to convert this entire json format dataset into DataFrame or tabular format.

In [98]:
s1

{'name': 'mohd irfan',
 'job': 'fresher',
 'phone_no': 93433953,
 'comp': ['tcs', 'wipro', 'microsoft', 'google', 'amazon']}

In [99]:
pd.DataFrame(s1)

         name      job  phone_no       comp
0  mohd irfan  fresher  93433953        tcs
1  mohd irfan  fresher  93433953      wipro
2  mohd irfan  fresher  93433953  microsoft
3  mohd irfan  fresher  93433953     google
4  mohd irfan  fresher  93433953     amazon

In [100]:
pd.DataFrame(s1, columns=['comp'])

        comp
0        tcs
1      wipro
2  microsoft
3     google
4     amazon

#### Let's import a complex json dataset and try various operations on it.

In [101]:
import requests

In [103]:
# Very complex json data like what we get in industries.
res = requests.get("https://api.github.com/repos/pandas-dev/pandas/issues")

In [104]:
res

In [106]:
js = res.json()

In [107]:
js  # dataset is available in the form of a list.

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47444',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47444/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47444/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47444/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/47444',
  'id': 1278103238,
  'node_id': 'PR_kwDOAA0YD846Avlo',
  'number': 47444,
  'title': 'PDEP-1: Purpose and guidelines for pandas enhancement proposals',
  'user': {'login': 'datapythonista',
   'id': 10058240,
   'node_id': 'MDQ6VXNlcjEwMDU4MjQw',
   'avatar_url': 'https://avatars.githubusercontent.com/u/10058240?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/datapythonista',
   'html_url': 'https://github.com/datapythonista',
   'followers_url': 'https://api.github.com/users/datapythonista/followers',
   'following_url': 'https://api.github.com/users/datapythonista/following{/other_user}',
   'gists_url': 'https://api.github.com/users/datapythonista/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/datapythonista/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/datapythonista/subscriptions',
   'organizations_url': 'https://api.github.com/users/datapythonista/orgs',
   'repos_url': 'https://api.github.com/users/datapythonista/repos',
   'events_url': 'https://api.github.com/users/datapythonista/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/datapythonista/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 1508144531,
    'node_id': 'MDU6TGFiZWwxNTA4MTQ0NTMx',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Web',
    'name': 'Web',
    'color': '23ef97',
    'default': False,
    'description': 'pandas website'},
   {'id': 4253279386,
    'node_id': 'LA_kwDOAA0YD879g-Sa',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/PDEP',
    'name': 'PDEP',
    'color': '4B02F8',
    'default': False,
    'description': 'pandas enhancement proposal'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2022-06-21T08:40:26Z',
  'updated_at': '2022-06-21T13:23:37Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47444',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/47444',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/47444.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/47444.patch',
   'merged_at': None},
  'body': 'Initial PDEP to define purpose and guidelines for pandas enhancement proposals (equivalent to PEPs or NEPs). **Feedback very welcome**.\r\n\r\nThis PR also makes the PDEPs public in the [roadmap page](https://pandas.pydata.org/about/roadmap.html) of our website.\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47444/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47444/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47443',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47443/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47443/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47443/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/47443',
  'id': 1277993588,
  'node_id': 'I_kwDOAA0YD85MLKJ0',
  'number': 47443,
  'title': 'CI/PERF: Windows builds fail due to potential MemoryErrors',
  'user': {'login': 'mroeschke',
   'id': 10647082,
   'node_id': 'MDQ6VXNlcjEwNjQ3MDgy',
   'avatar_url': 'https://avatars.githubusercontent.com/u/10647082?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/mroeschke',
   'html_url': 'https://github.com/mroeschke',
   'followers_url': 'https://api.github.com/users/mroeschke/followers',
   'following_url': 'https://api.github.com/users/mroeschke/following{/other_user}',
   'gists_url': 'https://api.github.com/users/mroeschke/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/mroeschke/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/mroeschke/subscriptions',
   'organizations_url': 'https://api.github.com/users/mroeschke/orgs',
   'repos_url': 'https://api.github.com/users/mroeschke/repos',
   'events_url': 'https://api.github.com/users/mroeschke/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/mroeschke/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 48070600,
    'node_id': 'MDU6TGFiZWw0ODA3MDYwMA==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/CI',
    'name': 'CI',
    'color': 'a2bca7',
    'default': False,
    'description': 'Continuous Integration'},
   {'id': 57186974,
    'node_id': 'MDU6TGFiZWw1NzE4Njk3NA==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Windows',
    'name': 'Windows',
    'color': 'fbca04',
    'default': False,
    'description': 'Windows OS'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2022-06-21T07:12:18Z',
  'updated_at': '2022-06-21T07:12:18Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'body': 'Debugging attempt: https://github.com/pandas-dev/pandas/pull/47318\r\n\r\nFirst PR exhibiting these failures: https://github.com/pandas-dev/pandas/pull/47299\r\n\r\n_May_ point to a potentially memory leak in recent non-nano changes.',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47443/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47443/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47442',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47442/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47442/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47442/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/47442',
  'id': 1277930659,
  'node_id': 'PR_kwDOAA0YD846AMJl',
  'number': 47442,
  'title': 'CI: start testing Python 3.11',
  'user': {'login': 'fangchenli',
   'id': 7614606,
   'node_id': 'MDQ6VXNlcjc2MTQ2MDY=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/7614606?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/fangchenli',
   'html_url': 'https://github.com/fangchenli',
   'followers_url': 'https://api.github.com/users/fangchenli/followers',
   'following_url': 'https://api.github.com/users/fangchenli/following{/other_user}',
   'gists_url': 'https://api.github.com/users/fangchenli/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/fangchenli/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/fangchenli/subscriptions',
   'organizations_url': 'https://api.github.com/users/fangchenli/orgs',
   'repos_url': 'https://api.github.com/users/fangchenli/repos',
   'events_url': 'https://api.github.com/users/fangchenli/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/fangchenli/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2022-06-21T05:57:11Z',
  'updated_at': '2022-06-21T06:38:11Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'draft': True,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47442',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/47442',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/47442.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/47442.patch',
   'merged_at': None},
  'body': '- [ ] closes #xxxx (Replace xxxx with the Github issue number)\r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47442/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47442/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47441',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47441/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47441/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47441/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/47441',
  'id': 1277899673,
  'node_id': 'PR_kwDOAA0YD846AFsg',
  'number': 47441,
  'title': 'DOC: Update v1.3.0 changelog to reflect breaking change in join dtypes',
  'user': {'login': 'guyrt',
   'id': 1184478,
   'node_id': 'MDQ6VXNlcjExODQ0Nzg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/1184478?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/guyrt',
   'html_url': 'https://github.com/guyrt',
   'followers_url': 'https://api.github.com/users/guyrt/followers',
   'following_url': 'https://api.github.com/users/guyrt/following{/other_user}',
   'gists_url': 'https://api.github.com/users/guyrt/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/guyrt/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/guyrt/subscriptions',
   'organizations_url': 'https://api.github.com/users/guyrt/orgs',
   'repos_url': 'https://api.github.com/users/guyrt/repos',
   'events_url': 'https://api.github.com/users/guyrt/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/guyrt/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 1,
  'created_at': '2022-06-21T05:07:17Z',
  'updated_at': '2022-06-21T11:04:46Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47441',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/47441',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/47441.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/47441.patch',
   'merged_at': None},
  'body': 'Minor update to old docs to reflect a change in how dtype is chosen in joins. Docs only.\r\n\r\n- [ * ] closes #47384 \r\n- [ n/a ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ n/a ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ n/a ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ n/a ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47441/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47441/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47440',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47440/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47440/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47440/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/47440',
  'id': 1277625114,
  'node_id': 'PR_kwDOAA0YD845_HCM',
  'number': 47440,
  'title': 'REF: stop passing self as arg from ExtensionArray methods',
  'user': {'login': 'brunocoutinhoo',
   'id': 64714922,
   'node_id': 'MDQ6VXNlcjY0NzE0OTIy',
   'avatar_url': 'https://avatars.githubusercontent.com/u/64714922?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/brunocoutinhoo',
   'html_url': 'https://github.com/brunocoutinhoo',
   'followers_url': 'https://api.github.com/users/brunocoutinhoo/followers',
   'following_url': 'https://api.github.com/users/brunocoutinhoo/following{/other_user}',
   'gists_url': 'https://api.github.com/users/brunocoutinhoo/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/brunocoutinhoo/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/brunocoutinhoo/subscriptions',
   'organizations_url': 'https://api.github.com/users/brunocoutinhoo/orgs',
   'repos_url': 'https://api.github.com/users/brunocoutinhoo/repos',
   'events_url': 'https://api.github.com/users/brunocoutinhoo/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/brunocoutinhoo/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 1,
  'created_at': '2022-06-21T01:45:26Z',
  'updated_at': '2022-06-21T02:23:31Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47440',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/47440',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/47440.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/47440.patch',
   'merged_at': None},
  'body': '- [ ] closes #46843\r\n- [ ] All [code checks passed].\r\n- [ ] Added [type annotations] to new arguments/methods/functions.\r\n\r\n🐼\r\n\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47440/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47440/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47439',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47439/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47439/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47439/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/47439',
  'id': 1277566637,
  'node_id': 'PR_kwDOAA0YD845-5v8',
  'number': 47439,
  'title': 'REF:  if statements merge + typehint correction',
  'user': {'login': 'gugazan',
   'id': 60269111,
   'node_id': 'MDQ6VXNlcjYwMjY5MTEx',
   'avatar_url': 'https://avatars.githubusercontent.com/u/60269111?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/gugazan',
   'html_url': 'https://github.com/gugazan',
   'followers_url': 'https://api.github.com/users/gugazan/followers',
   'following_url': 'https://api.github.com/users/gugazan/following{/other_user}',
   'gists_url': 'https://api.github.com/users/gugazan/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/gugazan/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/gugazan/subscriptions',
   'organizations_url': 'https://api.github.com/users/gugazan/orgs',
   'repos_url': 'https://api.github.com/users/gugazan/repos',
   'events_url': 'https://api.github.com/users/gugazan/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/gugazan/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 1,
  'created_at': '2022-06-21T01:06:11Z',
  'updated_at': '2022-06-21T10:55:07Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47439',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/47439',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/47439.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/47439.patch',
   'merged_at': None},
  'body': '- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n\r\n- if statements merge on `pandas/core/frame.py` and `pandas/io/xml.py`\r\n\r\n- Function `_generate_index_names_row()`  on `pandas/io/formats/style_render.py` expected a tuple as a parameter but its only reference uses a list, so i altered the typehint\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47439/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47439/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47438',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47438/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47438/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47438/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/47438',
  'id': 1277526493,
  'node_id': 'PR_kwDOAA0YD845-w3g',
  'number': 47438,
  'title': 'CLN: some simple code cleanup',
  'user': {'login': 'hydratedguy',
   'id': 32471918,
   'node_id': 'MDQ6VXNlcjMyNDcxOTE4',
   'avatar_url': 'https://avatars.githubusercontent.com/u/32471918?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/hydratedguy',
   'html_url': 'https://github.com/hydratedguy',

##### My objective is to extract all values of title keys from this json file.

In [109]:
js[0]['title']

'PDEP-1: Purpose and guidelines for pandas enhancement proposals'

In [116]:
for i in range(len(js)):
    print(js[i]['title'])

PDEP-1: Purpose and guidelines for pandas enhancement proposals
CI/PERF: Windows builds fail due to potential MemoryErrors
CI: start testing Python 3.11
DOC: Update v1.3.0 changelog to reflect breaking change in join dtypes
REF: stop passing self as arg from ExtensionArray methods
REF:  if statements merge + typehint correction
CLN: some simple code cleanup
DOC: clarify to_csv float format docstring
REF: simplify Timestamp.replace
Fix `vertical-align: middle;` for `Styler.to_excel` with xlsxwriter engine
DOC clarify inplace operation section in 1.5 whats_new
PERF: x.loc[x > 0.5] = 2 * x is 2x slower than x[x > 0.5] = 2 * x
Fix segmentation fault when JSON serializing a PeriodIndex
DOC: Add an interactive shell powered by JupyterLite to the website
TST: GH26650, added new test to validate numpy matmul function with dataframes
Documentation improvement regarding returned datatype of pandas.unique
BUG: DataFrame.setitem raising when rhs is ea dtype Series
BUG: Unexpected keyword argument `maxsplit` on `rsplit` even though it is accepted in vanilla Python
BUG: read_xml iterparse doesn't handle multiple toplevel elements with lxml parser
ENH: TDA.total_seconds support non-nano
Add tests
annotation, missing test case, perf DTA.mode
REF: GH38174 - Refactoring DataFrame.combine_first
CI: remove comment-bot
BUG: .fillna(-1) does not work in pd.eval
BUG: iterparse of read_xml not parsing duplicate element and attribute names
TYP: read_sas
BUG: pd.to_numeric doesn't return numeric dtype
PERF: Performance improvement on dataframe.update.
SAS7BDAT parser: Speed up RLE/RDC decompression

##### My objective is to convert this completely messed up json data having multiple nested dictionaries into DataFrame format.

In [118]:
df3 = pd.DataFrame(js)

In [129]:
df3.head()

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,closed_at,author_association,active_lock_reason,draft,pull_request,body,reactions,timeline_url,performed_via_github_app,state_reason
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47444,1278103238,PR_kwDOAA0YD846Avlo,47444,PDEP-1: Purpose and guidelines for pandas enha...,...,None,MEMBER,None,False,{'url': 'https://api.github.com/repos/pandas-d...,Initial PDEP to define purpose and guidelines ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47443,1277993588,I_kwDOAA0YD85MLKJ0,47443,CI/PERF: Windows builds fail due to potential ...,...,None,MEMBER,None,NaN,NaN,Debugging attempt: https://github.com/pandas-d...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47442,1277930659,PR_kwDOAA0YD846AMJl,47442,CI: start testing Python 3.11,...,None,MEMBER,None,True,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47441,1277899673,PR_kwDOAA0YD846AFsg,47441,DOC: Update v1.3.0 changelog to reflect breaki...,...,None,CONTRIBUTOR,None,False,{'url': 'https://api.github.com/repos/pandas-d...,Minor update to old docs to reflect a change i...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47440,1277625114,PR_kwDOAA0YD845_HCM,47440,REF: stop passing self as arg from ExtensionAr...,...,None,NONE,None,False,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #46843\r\n- [ ] All [code checks ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None

In [119]:
df3.to_csv("json_dump.csv")

In [ ]:
Here in the above dataset, key 'users' has value itself as dictionary.

In [121]:
df4 = js[0]['user']

In [126]:
#jjs = list(df4)
print([df4])

[{'login': 'datapythonista', 'id': 10058240, 'node_id': 'MDQ6VXNlcjEwMDU4MjQw', 'avatar_url': 'https://avatars.githubusercontent.com/u/10058240?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/datapythonista', 'html_url': 'https://github.com/datapythonista', 'followers_url': 'https://api.github.com/users/datapythonista/followers', 'following_url': 'https://api.github.com/users/datapythonista/following{/other_user}', 'gists_url': 'https://api.github.com/users/datapythonista/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/datapythonista/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/datapythonista/subscriptions', 'organizations_url': 'https://api.github.com/users/datapythonista/orgs', 'repos_url': 'https://api.github.com/users/datapythonista/repos', 'events_url': 'https://api.github.com/users/datapythonista/events{/privacy}', 'received_events_url': 'https://api.github.com/users/datapythonista/received_events', 'type': 'User', 'site_admin': False}]

In [125]:
df4

{'login': 'datapythonista',
 'id': 10058240,
 'node_id': 'MDQ6VXNlcjEwMDU4MjQw',
 'avatar_url': 'https://avatars.githubusercontent.com/u/10058240?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/datapythonista',
 'html_url': 'https://github.com/datapythonista',
 'followers_url': 'https://api.github.com/users/datapythonista/followers',
 'following_url': 'https://api.github.com/users/datapythonista/following{/other_user}',
 'gists_url': 'https://api.github.com/users/datapythonista/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/datapythonista/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/datapythonista/subscriptions',
 'organizations_url': 'https://api.github.com/users/datapythonista/orgs',
 'repos_url': 'https://api.github.com/users/datapythonista/repos',
 'events_url': 'https://api.github.com/users/datapythonista/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/datapythonista/received_events',
 'type': 'User',
 'site_admin': False}

In [127]:
pd.DataFrame([df4])

,login,id,node_id,avatar_url,gravatar_id,url,html_url,followers_url,following_url,gists_url,starred_url,subscriptions_url,organizations_url,repos_url,events_url,received_events_url,type,site_admin
0,datapythonista,10058240,MDQ6VXNlcjEwMDU4MjQw,https://avatars.githubusercontent.com/u/100582...,,https://api.github.com/users/datapythonista,https://github.com/datapythonista,https://api.github.com/users/datapythonista/fo...,https://api.github.com/users/datapythonista/fo...,https://api.github.com/users/datapythonista/gi...,https://api.github.com/users/datapythonista/st...,https://api.github.com/users/datapythonista/su...,https://api.github.com/users/datapythonista/orgs,https://api.github.com/users/datapythonista/repos,https://api.github.com/users/datapythonista/ev...,https://api.github.com/users/datapythonista/re...,User,False

In [130]:
ls = []
for i in range(len(js)):
    ls.append(js[i]['user'])
pd.DataFrame(ls)

,login,id,node_id,avatar_url,gravatar_id,url,html_url,followers_url,following_url,gists_url,starred_url,subscriptions_url,organizations_url,repos_url,events_url,received_events_url,type,site_admin
0,datapythonista,10058240,MDQ6VXNlcjEwMDU4MjQw,https://avatars.githubusercontent.com/u/100582...,,https://api.github.com/users/datapythonista,https://github.com/datapythonista,https://api.github.com/users/datapythonista/fo...,https://api.github.com/users/datapythonista/fo...,https://api.github.com/users/datapythonista/gi...,https://api.github.com/users/datapythonista/st...,https://api.github.com/users/datapythonista/su...,https://api.github.com/users/datapythonista/orgs,https://api.github.com/users/datapythonista/repos,https://api.github.com/users/datapythonista/ev...,https://api.github.com/users/datapythonista/re...,User,False
1,mroeschke,10647082,MDQ6VXNlcjEwNjQ3MDgy,https://avatars.githubusercontent.com/u/106470...,,https://api.github.com/users/mroeschke,https://github.com/mroeschke,https://api.github.com/users/mroeschke/followers,https://api.github.com/users/mroeschke/followi...,https://api.github.com/users/mroeschke/gists{/...,https://api.github.com/users/mroeschke/starred...,https://api.github.com/users/mroeschke/subscri...,https://api.github.com/users/mroeschke/orgs,https://api.github.com/users/mroeschke/repos,https://api.github.com/users/mroeschke/events{...,https://api.github.com/users/mroeschke/receive...,User,False
2,fangchenli,7614606,MDQ6VXNlcjc2MTQ2MDY=,https://avatars.githubusercontent.com/u/761460...,,https://api.github.com/users/fangchenli,https://github.com/fangchenli,https://api.github.com/users/fangchenli/followers,https://api.github.com/users/fangchenli/follow...,https://api.github.com/users/fangchenli/gists{...,https://api.github.com/users/fangchenli/starre...,https://api.github.com/users/fangchenli/subscr...,https://api.github.com/users/fangchenli/orgs,https://api.github.com/users/fangchenli/repos,https://api.github.com/users/fangchenli/events...,https://api.github.com/users/fangchenli/receiv...,User,False
3,guyrt,1184478,MDQ6VXNlcjExODQ0Nzg=,https://avatars.githubusercontent.com/u/118447...,,https://api.github.com/users/guyrt,https://github.com/guyrt,https://api.github.com/users/guyrt/followers,https://api.github.com/users/guyrt/following{/...,https://api.github.com/users/guyrt/gists{/gist...,https://api.github.com/users/guyrt/starred{/ow...,https://api.github.com/users/guyrt/subscriptions,https://api.github.com/users/guyrt/orgs,https://api.github.com/users/guyrt/repos,https://api.github.com/users/guyrt/events{/pri...,https://api.github.com/users/guyrt/received_ev...,User,False
4,brunocoutinhoo,64714922,MDQ6VXNlcjY0NzE0OTIy,https://avatars.githubusercontent.com/u/647149...,,https://api.github.com/users/brunocoutinhoo,https://github.com/brunocoutinhoo,https://api.github.com/users/brunocoutinhoo/fo...,https://api.github.com/users/brunocoutinhoo/fo...,https://api.github.com/users/brunocoutinhoo/gi...,https://api.github.com/users/brunocoutinhoo/st...,https://api.github.com/users/brunocoutinhoo/su...,https://api.github.com/users/brunocoutinhoo/orgs,https://api.github.com/users/brunocoutinhoo/repos,https://api.github.com/users/brunocoutinhoo/ev...,https://api.github.com/users/brunocoutinhoo/re...,User,False
5,gugazan,60269111,MDQ6VXNlcjYwMjY5MTEx,https://avatars.githubusercontent.com/u/602691...,,https://api.github.com/users/gugazan,https://github.com/gugazan,https://api.github.com/users/gugazan/followers,https://api.github.com/users/gugazan/following...,https://api.github.com/users/gugazan/gists{/gi...,https://api.github.com/users/gugazan/starred{/...,https://api.github.com/users/gugazan/subscript...,https://api.github.com/users/gugazan/orgs,https://api.github.com/users/gugazan/repos,https://api.github.com/users/gugazan/events{/p...,https://api.github.com/users/gugazan/received_...,User,False
6,hydratedguy,32471918,MDQ6VXNlcjMyNDcxOTE4,https://avatars.githubusercontent.com/u/324719...,,https://api.github.com/users/hydratedguy,https://github.com/hydratedguy,https://api.github.com/users/hydratedguy/follo...,https://api.github.com/users/hydratedguy/follo...,https://api.github.com/users/hydratedguy/gists...,https://api.github.com/users/hydratedguy/starr...,https://api.github.com/users/hydratedguy/subsc...,https://api.github.com/users/hydratedguy/orgs,https://api.github.com/users/hydratedguy/repos,https://api.github.com/users/hydratedguy/event...,https://api.github.com/users/hydratedguy/recei...,User,False
7,phofl,61934744,MDQ6VXNlcjYxOTM0NzQ0,https://avatars.githubusercontent.com/u/619347...,,https://api.github.com/users/phofl,https://github.com/phofl,https://api.github.com/users/phofl/followers,https://api.github.com/users/phofl/following{/...,https://api.github.com/users/phofl/gists{/gist...,https://api.github.com/users/phofl/starred{/ow...,https://api.github.com/users/phofl/subscriptions,https://api.github.com/users/phofl/orgs,https://api.github.com/users/phofl/repos,https://api.github.com/users/phofl/events{/pri...,https://api.github.com/users/phofl/received_ev...,User,False
8,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
9,tehunter,7980666,MDQ6VXNlcjc5ODA2NjY=,https://avatars.githubusercontent.com/u/798066...,,https://api.github.com/users/tehunter,https://github.com/tehunter,https://api.github.com/users/tehunter/followers,https://api.github.com/users/tehunter/followin...,https://api.github.com/users/tehunter/gists{/g...,https://api.github.com/users/tehunter/starred{...,https://api.github.com/users/tehunter/subscrip...,https://api.github.com/users/tehunter/orgs,https://api.github.com/users/tehunter/repos,https://api.github.com/users/tehunter/events{/...,https://api.github.com/users/tehunter/received...,User,False
10,lesteve,1680079,MDQ6VXNlcjE2ODAwNzk=,https://avatars.githubusercontent.com/u/168007...,,https://api.github.com/users/lesteve,https://github.com/lesteve,https://api.github.com/users/lesteve/followers,https://api.github.com/users/lesteve/following...,https://api.github.com/users/lesteve/gists{/gi...,https://api.github.com/users/lesteve/starred{/...,https://api.github.com/users/lesteve/subscript...,https://api.github.com/users/lesteve/orgs,https://api.github.com/users/lesteve/repos,https://api.github.com/users/lesteve/events{/p...,https://api.github.com/users/lesteve/received_...,User,False
11,colinfang,1499555,MDQ6VXNlcjE0OTk1NTU=,https://avatars.githubusercontent.com/u/149955...,,https://api.github.com/users/colinfang,https://github.com/colinfang,https://api.github.com/users/colinfang/followers,https://api.github.com/users/colinfang/followi...,https://api.github.com/users/colinfang/gists{/...,https://api.github.com/users/colinfang/starred...,https://api.github.com/users/colinfang/subscri...,https://api.github.com/users/colinfang/orgs,https://api.github.com/users/colinfang/repos,https://api.github.com/users/colinfang/events{...,https://api.github.com/users/colinfang/receive...,User,False
12,roberthdevries,10944368,MDQ6VXNlcjEwOTQ0MzY4,https://avatars.githubusercontent.com/u/109443...,,https://api.github.com/users/roberthdevries,https://github.com/roberthdevries,https://api.github.com/users/roberthdevries/fo...,https://api.github.com/users/roberthdevries/fo...,https://api.github.com/users/roberthdevries/gi...,https://api.github.com/users/roberthdevries/st...,https://api.github.com/users/roberthdevries/su...,https://api.github.com/users/roberthdevries/orgs,https://api.github.com/users/roberthdevries/repos,https://api.github.com/users/roberthdevries/ev...,https://api.github.com/users/roberthdevries/re...,User,False
13,jtpio,591645,MDQ6VXNlcjU5MTY0NQ==,https://avatars.githubusercontent.com/u/591645...,,https://api.github.com/users/jtpio,https://github.com/jtpio,https://api.github.com/users/jtpio/followers,https://api.github.com/users/jtpio/following{/...,https://api.github.com/users/jtpio/gists{/gist...,https://api.github.com/users/jtpio/starred{/ow...,https://api.github.com/users/jtpio/subscriptions,https://api.github.com/users/jtpio/orgs,https://api.github.com/users/jtpio/repos,https://api.github.com/users/jtpio/events{/pri...,https://api.github.com/users/jtpio/received_ev...,User,False
14,carbonleakage,71427714,MDQ6VXNlcjcxNDI3NzE0,https://avatars.githubusercontent.com/u/714277...,,https://api.github.com/users/carbonleakage,https://github.com/carbonleakage,https://api.github.com/users/carbonleakage/fol...,https://api.github.com/users/carbonleakage/fol...,https://api.github.com/users/carbonleakage/gis...,https://api.github.com/users/carbonleakage/sta...,https://api.github.com/users/carbonleakage/sub...,https://api.github.com/users/carbonleakage/orgs,https://api.github.com/users/carbonleakage/repos,https://api.github.com/users/carbonleakage/eve...,https://api.github.com/users/carbonleakage/rec...,User,False
15,pavelsr,1158473,MDQ6VXNlcjExNTg0NzM=,https://avatars.githubusercontent.com/u/115847...,,https://api.github.com/users/pavelsr,https://github.com/pavelsr,https://api.github.com/users/pavelsr/followers,https://api.github.com/users/pavelsr/following...,https://api.github.com/users/pavelsr/gists{/gi...,https://api.github.com/users/pavelsr/starred{/...,https://api.github.com/users/pavelsr/subscript...,https://api.github.com/users/pavelsr/orgs,https://api.github.com/users/pavelsr/repos,https://api.github.com/users/pavelsr/events{/p...,https://api.github.com/users/pavelsr/received_...,User,False
16,phofl,61934744,MDQ6VXNlcjYxOTM0NzQ0,https://avatars.githubusercontent.com/u/619347...,,https://api.github.com/users/phofl,https://github.com/phofl,https://api.github.com/users/phofl/followers,https://api.github.com/users/phofl/following{/...,https://api.github.com/users/phofl/gists{/gist...,https://api.github.com/users/phofl/starred{/ow...,https://api.github.com/users/phofl/subscriptions,https://api.github.com/users/phofl/orgs,https://api.github.com/users/phofl/repos,https://api.github.com/users/phofl/events{/pri...,https://api.github.com/users/phofl/received_ev...,User,False
17,paw-lu,30049606,MDQ6VXNlcjMwMDQ5NjA2,https://avatars.githubusercontent.com/u/300496...,,https://api.github.com/users/paw-lu,https://github.com/paw-lu,https://api.github.com/users/paw-lu/followers,https://api.github.com/users/paw-lu/following{...,https://api.github.com/users/paw-lu/gists{/gis...,https://api.github.com/users/paw-lu/starred{/o...,https://api.github.com/users/paw-lu/subscriptions,https://api.github.com/users/paw-lu/orgs,https://api.github.com/users/paw-lu/repos,https://api.github.com/users/paw-lu/events{/pr...,https://api.github.com/users/paw-lu/received_e...,User,False
18,bailsman,932518,MDQ6VXNlcjkzMjUxOA==,https://avatars.githubusercontent.com/u/932518...,,https://api.github.com/users/bailsman,https://github.com/bailsman,https://api.github.com/users/bailsman/followers,https://api.github.com/users/bailsman/followin...,https://api.github.com/users/bailsman/gists{/g...,https://api.github.com/users/bailsman/starred{...,https://api.github.com/users/bailsman/subscrip...,https://api.github.com/users/bailsman/orgs,https://api.github.com/users/bailsman/repos,https://api.github.com/users/bailsman/events{/...,https://api.github.com/users/bailsman/received...,User,False
19,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
20,jackgoldsmith4,22875722,MDQ6VXNlcjIyODc1NzIy,https://avatars.githubusercontent.com/u/228757...,,https://api.github.com/users/jackgoldsmith4,https://github.com/jackgoldsmith4,https://api.github.com/users/jackgoldsmith4/fo...,https://api.github.com/users/jackgoldsmith4/fo...,https://api.github.com/users/jackgoldsmith4/gi...,https://api.github.com/users/jackgoldsmith4/st...,https://api.github.com/users/jackgoldsmith4/su...,https://api.github.com/users/jackgoldsmith4/orgs,https://api.github.com/users/jackgoldsmith4/repos,https://api.github.com/users/jackgoldsmith4/ev...,https://api.github.com/users/jackgoldsmith4/re...,User,False
21,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
22,hydratedguy,32471918,MDQ6VXNlcjMyNDcxOTE4,https://avatars.githubusercontent.com/u/324719...,,https://api.github.com/users/hydratedguy,https://github.com/hydratedguy,https://api.github.com/users/hydratedguy/follo...,https://api.github.com/users/hydratedguy/follo...,https://api.github.com/users/hydratedguy/gists...,https://api.github.com/users/hydratedguy/starr...,https://api.github.com/users/hydratedguy/subsc...,https://api.github.com/users/hydratedguy/orgs,https://api.github.com/users/hydratedguy/repos,https://api.github.com/users/hydratedguy/event...,https://api.github.com/users/hydratedguy/recei...,User,False
23,MarcoGorelli,33491632,MDQ6VXNlcjMzNDkxNjMy,https://avatars.githubusercontent.com/u/334916...,,https://api.github.com/users/MarcoGorelli,https://github.com/MarcoGorelli,https://api.github.com/users/MarcoGorelli/foll...,https://api.github.com/users/MarcoGorelli/foll...,https://api.github.com/users/MarcoGorelli/gist...,https://api.github.com/users/MarcoGorelli/star...,https://api.github.com/users/MarcoGorelli/subs...,https://api.github.com/users/MarcoGorelli/orgs,https://api.github.com/users/MarcoGorelli/repos,https://api.github.com/users/MarcoGorelli/even...,https://api.github.com/users/MarcoGorelli/rece...,User,False
24,shyamsantoki,56479219,MDQ6VXNlcjU2NDc5MjE5,https://avatars.githubusercontent.com/u/564792...,,https://api.github.com/users/shyamsantoki,https://github.com/shyamsantoki,https://api.github.com/users/shyamsantoki/foll...,https://api.github.com/users/shyamsantoki/foll...,https://api.github.com/users/shyamsantoki/gist...,https://api.github.com/users/shyamsantoki/star...,https://api.github.com/users/shyamsantoki/subs...,https://api.github.com/users/shyamsantoki/orgs,https://api.github.com/users/shyamsantoki/repos,https://api.github.com/users/shyamsantoki/even...,https://api.github.com/users/shyamsantoki/rece...,User,False
25,ParfaitG,13602663,MDQ6VXNlcjEzNjAyNjYz,https://avatars.githubusercontent.com/u/136026...,,https://api.github.com/users/ParfaitG,https://github.com/ParfaitG,https://api.github.com/users/ParfaitG/followers,https://api.github.com/users/ParfaitG/followin...,https://api.github.com/users/ParfaitG/gists{/g...,https://api.github.com/users/ParfaitG/starred{...,https://api.github.com/users/ParfaitG/subscrip...,https://api.github.com/users/ParfaitG/orgs,https://api.github.com/users/ParfaitG/repos,https://api.github.com/users/ParfaitG/events{/...,https://api.github.com/users/ParfaitG/received...,User,False
26,twoertwein,6618166,MDQ6VXNlcjY2MTgxNjY=,https://avatars.githubusercontent.com/u/661816...,,https://api.github.com/users/twoertwein,https://github.com/twoertwein,https://api.github.com/users/twoertwein/followers,https://api.github.com/users/twoertwein/follow...,https://api.github.com/users/twoertwein/gists{...,https://api.github.com/users/twoertwein/starre...,https://api.github.com/users/twoertwein/subscr...,https://api.github.com/users/twoertwein/orgs,https://api.github.com/users/twoertwein/repos,https://api.github.com/users/twoertwein/events...,https://api.github.com/users/twoertwein/receiv...,User,False
27,QuentinBlampey,33903498,MDQ6VXNlcjMzOTAzNDk4,https://avatars.githubusercontent.com/u/339034...,,https://api.github.com/users/QuentinBlampey,https://github.com/QuentinBlampey,https://api.github.com/users/QuentinBlampey/fo...,https://api.github.com/users/QuentinBlampey/fo...,https://api.github.com/users/QuentinBlampey/gi...,https://api.github.com/users/QuentinBlampey/st...,https://api.github.com/users/QuentinBlampey/su...,https://api.github.com/users/QuentinBlampey/orgs,https://api.github.com/users/QuentinBlampey/repos,https://api.github.com/users/QuentinBlampey/ev...,https://api.github.com/users/QuentinBlampey/re...,User,False
28,warm200,5666546,MDQ6VXNlcjU2NjY1NDY=,https://avatars.githubusercontent.com/u/566654...,,https://api.github.com/users/warm200,https://github.com/warm200,https://api.github.com/users/warm200/followers,https://api.github.com/users/warm200/following...,https://api.github.com/users/warm200/gists{/gi...,https://api.github.com/users/warm200/starred{/...,https://api.github.com/users/warm200/subscript...,https://api.github.com/users/warm200/orgs,https://api.github.com/users/warm200/repos,https://api.github.com/users/warm200/events{/p...,https://api.github.com/users/warm200/received_...,User,False
29,jonashaag,175722,MDQ6VXNlcjE3NTcyMg==,https://avatars.githubusercontent.com/u/175722...,,https://api.github.com/users/jonashaag,https://github.com/jonashaag,https://api.github.com/users/jonashaag/followers,https://api.github.com/users/jonashaag/followi...,https://api.github.com/users/jonashaag/gists{/...,https://api.github.com/users/jonashaag/starred...,https://api.github.com/users/jonashaag/subscri...,https://api.github.com/users/jonashaag/orgs,https://api.github.com/users/jonashaag/repos,https://api.github.com/users/jonashaag/events{...,https://api.github.com/users/jonashaag/receive...,User,False

In [131]:
pd.DataFrame([js[i]['user'] for i in range(len(js))])

,login,id,node_id,avatar_url,gravatar_id,url,html_url,followers_url,following_url,gists_url,starred_url,subscriptions_url,organizations_url,repos_url,events_url,received_events_url,type,site_admin
0,datapythonista,10058240,MDQ6VXNlcjEwMDU4MjQw,https://avatars.githubusercontent.com/u/100582...,,https://api.github.com/users/datapythonista,https://github.com/datapythonista,https://api.github.com/users/datapythonista/fo...,https://api.github.com/users/datapythonista/fo...,https://api.github.com/users/datapythonista/gi...,https://api.github.com/users/datapythonista/st...,https://api.github.com/users/datapythonista/su...,https://api.github.com/users/datapythonista/orgs,https://api.github.com/users/datapythonista/repos,https://api.github.com/users/datapythonista/ev...,https://api.github.com/users/datapythonista/re...,User,False
1,mroeschke,10647082,MDQ6VXNlcjEwNjQ3MDgy,https://avatars.githubusercontent.com/u/106470...,,https://api.github.com/users/mroeschke,https://github.com/mroeschke,https://api.github.com/users/mroeschke/followers,https://api.github.com/users/mroeschke/followi...,https://api.github.com/users/mroeschke/gists{/...,https://api.github.com/users/mroeschke/starred...,https://api.github.com/users/mroeschke/subscri...,https://api.github.com/users/mroeschke/orgs,https://api.github.com/users/mroeschke/repos,https://api.github.com/users/mroeschke/events{...,https://api.github.com/users/mroeschke/receive...,User,False
2,fangchenli,7614606,MDQ6VXNlcjc2MTQ2MDY=,https://avatars.githubusercontent.com/u/761460...,,https://api.github.com/users/fangchenli,https://github.com/fangchenli,https://api.github.com/users/fangchenli/followers,https://api.github.com/users/fangchenli/follow...,https://api.github.com/users/fangchenli/gists{...,https://api.github.com/users/fangchenli/starre...,https://api.github.com/users/fangchenli/subscr...,https://api.github.com/users/fangchenli/orgs,https://api.github.com/users/fangchenli/repos,https://api.github.com/users/fangchenli/events...,https://api.github.com/users/fangchenli/receiv...,User,False
3,guyrt,1184478,MDQ6VXNlcjExODQ0Nzg=,https://avatars.githubusercontent.com/u/118447...,,https://api.github.com/users/guyrt,https://github.com/guyrt,https://api.github.com/users/guyrt/followers,https://api.github.com/users/guyrt/following{/...,https://api.github.com/users/guyrt/gists{/gist...,https://api.github.com/users/guyrt/starred{/ow...,https://api.github.com/users/guyrt/subscriptions,https://api.github.com/users/guyrt/orgs,https://api.github.com/users/guyrt/repos,https://api.github.com/users/guyrt/events{/pri...,https://api.github.com/users/guyrt/received_ev...,User,False
4,brunocoutinhoo,64714922,MDQ6VXNlcjY0NzE0OTIy,https://avatars.githubusercontent.com/u/647149...,,https://api.github.com/users/brunocoutinhoo,https://github.com/brunocoutinhoo,https://api.github.com/users/brunocoutinhoo/fo...,https://api.github.com/users/brunocoutinhoo/fo...,https://api.github.com/users/brunocoutinhoo/gi...,https://api.github.com/users/brunocoutinhoo/st...,https://api.github.com/users/brunocoutinhoo/su...,https://api.github.com/users/brunocoutinhoo/orgs,https://api.github.com/users/brunocoutinhoo/repos,https://api.github.com/users/brunocoutinhoo/ev...,https://api.github.com/users/brunocoutinhoo/re...,User,False
5,gugazan,60269111,MDQ6VXNlcjYwMjY5MTEx,https://avatars.githubusercontent.com/u/602691...,,https://api.github.com/users/gugazan,https://github.com/gugazan,https://api.github.com/users/gugazan/followers,https://api.github.com/users/gugazan/following...,https://api.github.com/users/gugazan/gists{/gi...,https://api.github.com/users/gugazan/starred{/...,https://api.github.com/users/gugazan/subscript...,https://api.github.com/users/gugazan/orgs,https://api.github.com/users/gugazan/repos,https://api.github.com/users/gugazan/events{/p...,https://api.github.com/users/gugazan/received_...,User,False
6,hydratedguy,32471918,MDQ6VXNlcjMyNDcxOTE4,https://avatars.githubusercontent.com/u/324719...,,https://api.github.com/users/hydratedguy,https://github.com/hydratedguy,https://api.github.com/users/hydratedguy/follo...,https://api.github.com/users/hydratedguy/follo...,https://api.github.com/users/hydratedguy/gists...,https://api.github.com/users/hydratedguy/starr...,https://api.github.com/users/hydratedguy/subsc...,https://api.github.com/users/hydratedguy/orgs,https://api.github.com/users/hydratedguy/repos,https://api.github.com/users/hydratedguy/event...,https://api.github.com/users/hydratedguy/recei...,User,False
7,phofl,61934744,MDQ6VXNlcjYxOTM0NzQ0,https://avatars.githubusercontent.com/u/619347...,,https://api.github.com/users/phofl,https://github.com/phofl,https://api.github.com/users/phofl/followers,https://api.github.com/users/phofl/following{/...,https://api.github.com/users/phofl/gists{/gist...,https://api.github.com/users/phofl/starred{/ow...,https://api.github.com/users/phofl/subscriptions,https://api.github.com/users/phofl/orgs,https://api.github.com/users/phofl/repos,https://api.github.com/users/phofl/events{/pri...,https://api.github.com/users/phofl/received_ev...,User,False
8,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
9,tehunter,7980666,MDQ6VXNlcjc5ODA2NjY=,https://avatars.githubusercontent.com/u/798066...,,https://api.github.com/users/tehunter,https://github.com/tehunter,https://api.github.com/users/tehunter/followers,https://api.github.com/users/tehunter/followin...,https://api.github.com/users/tehunter/gists{/g...,https://api.github.com/users/tehunter/starred{...,https://api.github.com/users/tehunter/subscrip...,https://api.github.com/users/tehunter/orgs,https://api.github.com/users/tehunter/repos,https://api.github.com/users/tehunter/events{/...,https://api.github.com/users/tehunter/received...,User,False
10,lesteve,1680079,MDQ6VXNlcjE2ODAwNzk=,https://avatars.githubusercontent.com/u/168007...,,https://api.github.com/users/lesteve,https://github.com/lesteve,https://api.github.com/users/lesteve/followers,https://api.github.com/users/lesteve/following...,https://api.github.com/users/lesteve/gists{/gi...,https://api.github.com/users/lesteve/starred{/...,https://api.github.com/users/lesteve/subscript...,https://api.github.com/users/lesteve/orgs,https://api.github.com/users/lesteve/repos,https://api.github.com/users/lesteve/events{/p...,https://api.github.com/users/lesteve/received_...,User,False
11,colinfang,1499555,MDQ6VXNlcjE0OTk1NTU=,https://avatars.githubusercontent.com/u/149955...,,https://api.github.com/users/colinfang,https://github.com/colinfang,https://api.github.com/users/colinfang/followers,https://api.github.com/users/colinfang/followi...,https://api.github.com/users/colinfang/gists{/...,https://api.github.com/users/colinfang/starred...,https://api.github.com/users/colinfang/subscri...,https://api.github.com/users/colinfang/orgs,https://api.github.com/users/colinfang/repos,https://api.github.com/users/colinfang/events{...,https://api.github.com/users/colinfang/receive...,User,False
12,roberthdevries,10944368,MDQ6VXNlcjEwOTQ0MzY4,https://avatars.githubusercontent.com/u/109443...,,https://api.github.com/users/roberthdevries,https://github.com/roberthdevries,https://api.github.com/users/roberthdevries/fo...,https://api.github.com/users/roberthdevries/fo...,https://api.github.com/users/roberthdevries/gi...,https://api.github.com/users/roberthdevries/st...,https://api.github.com/users/roberthdevries/su...,https://api.github.com/users/roberthdevries/orgs,https://api.github.com/users/roberthdevries/repos,https://api.github.com/users/roberthdevries/ev...,https://api.github.com/users/roberthdevries/re...,User,False
13,jtpio,591645,MDQ6VXNlcjU5MTY0NQ==,https://avatars.githubusercontent.com/u/591645...,,https://api.github.com/users/jtpio,https://github.com/jtpio,https://api.github.com/users/jtpio/followers,https://api.github.com/users/jtpio/following{/...,https://api.github.com/users/jtpio/gists{/gist...,https://api.github.com/users/jtpio/starred{/ow...,https://api.github.com/users/jtpio/subscriptions,https://api.github.com/users/jtpio/orgs,https://api.github.com/users/jtpio/repos,https://api.github.com/users/jtpio/events{/pri...,https://api.github.com/users/jtpio/received_ev...,User,False
14,carbonleakage,71427714,MDQ6VXNlcjcxNDI3NzE0,https://avatars.githubusercontent.com/u/714277...,,https://api.github.com/users/carbonleakage,https://github.com/carbonleakage,https://api.github.com/users/carbonleakage/fol...,https://api.github.com/users/carbonleakage/fol...,https://api.github.com/users/carbonleakage/gis...,https://api.github.com/users/carbonleakage/sta...,https://api.github.com/users/carbonleakage/sub...,https://api.github.com/users/carbonleakage/orgs,https://api.github.com/users/carbonleakage/repos,https://api.github.com/users/carbonleakage/eve...,https://api.github.com/users/carbonleakage/rec...,User,False
15,pavelsr,1158473,MDQ6VXNlcjExNTg0NzM=,https://avatars.githubusercontent.com/u/115847...,,https://api.github.com/users/pavelsr,https://github.com/pavelsr,https://api.github.com/users/pavelsr/followers,https://api.github.com/users/pavelsr/following...,https://api.github.com/users/pavelsr/gists{/gi...,https://api.github.com/users/pavelsr/starred{/...,https://api.github.com/users/pavelsr/subscript...,https://api.github.com/users/pavelsr/orgs,https://api.github.com/users/pavelsr/repos,https://api.github.com/users/pavelsr/events{/p...,https://api.github.com/users/pavelsr/received_...,User,False
16,phofl,61934744,MDQ6VXNlcjYxOTM0NzQ0,https://avatars.githubusercontent.com/u/619347...,,https://api.github.com/users/phofl,https://github.com/phofl,https://api.github.com/users/phofl/followers,https://api.github.com/users/phofl/following{/...,https://api.github.com/users/phofl/gists{/gist...,https://api.github.com/users/phofl/starred{/ow...,https://api.github.com/users/phofl/subscriptions,https://api.github.com/users/phofl/orgs,https://api.github.com/users/phofl/repos,https://api.github.com/users/phofl/events{/pri...,https://api.github.com/users/phofl/received_ev...,User,False
17,paw-lu,30049606,MDQ6VXNlcjMwMDQ5NjA2,https://avatars.githubusercontent.com/u/300496...,,https://api.github.com/users/paw-lu,https://github.com/paw-lu,https://api.github.com/users/paw-lu/followers,https://api.github.com/users/paw-lu/following{...,https://api.github.com/users/paw-lu/gists{/gis...,https://api.github.com/users/paw-lu/starred{/o...,https://api.github.com/users/paw-lu/subscriptions,https://api.github.com/users/paw-lu/orgs,https://api.github.com/users/paw-lu/repos,https://api.github.com/users/paw-lu/events{/pr...,https://api.github.com/users/paw-lu/received_e...,User,False
18,bailsman,932518,MDQ6VXNlcjkzMjUxOA==,https://avatars.githubusercontent.com/u/932518...,,https://api.github.com/users/bailsman,https://github.com/bailsman,https://api.github.com/users/bailsman/followers,https://api.github.com/users/bailsman/followin...,https://api.github.com/users/bailsman/gists{/g...,https://api.github.com/users/bailsman/starred{...,https://api.github.com/users/bailsman/subscrip...,https://api.github.com/users/bailsman/orgs,https://api.github.com/users/bailsman/repos,https://api.github.com/users/bailsman/events{/...,https://api.github.com/users/bailsman/received...,User,False
19,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
20,jackgoldsmith4,22875722,MDQ6VXNlcjIyODc1NzIy,https://avatars.githubusercontent.com/u/228757...,,https://api.github.com/users/jackgoldsmith4,https://github.com/jackgoldsmith4,https://api.github.com/users/jackgoldsmith4/fo...,https://api.github.com/users/jackgoldsmith4/fo...,https://api.github.com/users/jackgoldsmith4/gi...,https://api.github.com/users/jackgoldsmith4/st...,https://api.github.com/users/jackgoldsmith4/su...,https://api.github.com/users/jackgoldsmith4/orgs,https://api.github.com/users/jackgoldsmith4/repos,https://api.github.com/users/jackgoldsmith4/ev...,https://api.github.com/users/jackgoldsmith4/re...,User,False
21,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
22,hydratedguy,32471918,MDQ6VXNlcjMyNDcxOTE4,https://avatars.githubusercontent.com/u/324719...,,https://api.github.com/users/hydratedguy,https://github.com/hydratedguy,https://api.github.com/users/hydratedguy/follo...,https://api.github.com/users/hydratedguy/follo...,https://api.github.com/users/hydratedguy/gists...,https://api.github.com/users/hydratedguy/starr...,https://api.github.com/users/hydratedguy/subsc...,https://api.github.com/users/hydratedguy/orgs,https://api.github.com/users/hydratedguy/repos,https://api.github.com/users/hydratedguy/event...,https://api.github.com/users/hydratedguy/recei...,User,False
23,MarcoGorelli,33491632,MDQ6VXNlcjMzNDkxNjMy,https://avatars.githubusercontent.com/u/334916...,,https://api.github.com/users/MarcoGorelli,https://github.com/MarcoGorelli,https://api.github.com/users/MarcoGorelli/foll...,https://api.github.com/users/MarcoGorelli/foll...,https://api.github.com/users/MarcoGorelli/gist...,https://api.github.com/users/MarcoGorelli/star...,https://api.github.com/users/MarcoGorelli/subs...,https://api.github.com/users/MarcoGorelli/orgs,https://api.github.com/users/MarcoGorelli/repos,https://api.github.com/users/MarcoGorelli/even...,https://api.github.com/users/MarcoGorelli/rece...,User,False
24,shyamsantoki,56479219,MDQ6VXNlcjU2NDc5MjE5,https://avatars.githubusercontent.com/u/564792...,,https://api.github.com/users/shyamsantoki,https://github.com/shyamsantoki,https://api.github.com/users/shyamsantoki/foll...,https://api.github.com/users/shyamsantoki/foll...,https://api.github.com/users/shyamsantoki/gist...,https://api.github.com/users/shyamsantoki/star...,https://api.github.com/users/shyamsantoki/subs...,https://api.github.com/users/shyamsantoki/orgs,https://api.github.com/users/shyamsantoki/repos,https://api.github.com/users/shyamsantoki/even...,https://api.github.com/users/shyamsantoki/rece...,User,False
25,ParfaitG,13602663,MDQ6VXNlcjEzNjAyNjYz,https://avatars.githubusercontent.com/u/136026...,,https://api.github.com/users/ParfaitG,https://github.com/ParfaitG,https://api.github.com/users/ParfaitG/followers,https://api.github.com/users/ParfaitG/followin...,https://api.github.com/users/ParfaitG/gists{/g...,https://api.github.com/users/ParfaitG/starred{...,https://api.github.com/users/ParfaitG/subscrip...,https://api.github.com/users/ParfaitG/orgs,https://api.github.com/users/ParfaitG/repos,https://api.github.com/users/ParfaitG/events{/...,https://api.github.com/users/ParfaitG/received...,User,False
26,twoertwein,6618166,MDQ6VXNlcjY2MTgxNjY=,https://avatars.githubusercontent.com/u/661816...,,https://api.github.com/users/twoertwein,https://github.com/twoertwein,https://api.github.com/users/twoertwein/followers,https://api.github.com/users/twoertwein/follow...,https://api.github.com/users/twoertwein/gists{...,https://api.github.com/users/twoertwein/starre...,https://api.github.com/users/twoertwein/subscr...,https://api.github.com/users/twoertwein/orgs,https://api.github.com/users/twoertwein/repos,https://api.github.com/users/twoertwein/events...,https://api.github.com/users/twoertwein/receiv...,User,False
27,QuentinBlampey,33903498,MDQ6VXNlcjMzOTAzNDk4,https://avatars.githubusercontent.com/u/339034...,,https://api.github.com/users/QuentinBlampey,https://github.com/QuentinBlampey,https://api.github.com/users/QuentinBlampey/fo...,https://api.github.com/users/QuentinBlampey/fo...,https://api.github.com/users/QuentinBlampey/gi...,https://api.github.com/users/QuentinBlampey/st...,https://api.github.com/users/QuentinBlampey/su...,https://api.github.com/users/QuentinBlampey/orgs,https://api.github.com/users/QuentinBlampey/repos,https://api.github.com/users/QuentinBlampey/ev...,https://api.github.com/users/QuentinBlampey/re...,User,False
28,warm200,5666546,MDQ6VXNlcjU2NjY1NDY=,https://avatars.githubusercontent.com/u/566654...,,https://api.github.com/users/warm200,https://github.com/warm200,https://api.github.com/users/warm200/followers,https://api.github.com/users/warm200/following...,https://api.github.com/users/warm200/gists{/gi...,https://api.github.com/users/warm200/starred{/...,https://api.github.com/users/warm200/subscript...,https://api.github.com/users/warm200/orgs,https://api.github.com/users/warm200/repos,https://api.github.com/users/warm200/events{/p...,https://api.github.com/users/warm200/received_...,User,False
29,jonashaag,175722,MDQ6VXNlcjE3NTcyMg==,https://avatars.githubusercontent.com/u/175722...,,https://api.github.com/users/jonashaag,https://github.com/jonashaag,https://api.github.com/users/jonashaag/followers,https://api.github.com/users/jonashaag/followi...,https://api.github.com/users/jonashaag/gists{/...,https://api.github.com/users/jonashaag/starred...,https://api.github.com/users/jonashaag/subscri...,https://api.github.com/users/jonashaag/orgs,https://api.github.com/users/jonashaag/repos,https://api.github.com/users/jonashaag/events{...,https://api.github.com/users/jonashaag/receive...,User,False

In [1]:
import pandas as pd

In [3]:
from_file = pd.read_csv("basketball_Data.csv")

### Serialization
Serialization is the act of transforming a structured object into a sequence of bytes that can be stored in a file system, database, or communicated over the network.

Serialization is the process of encoding complex data into a stream of bytes in such a way that it can be converted back into the original data by a second operation. This can be used to store data or send it across a network.

#### Pickling is a kind of binary file/data format in pandas. Pickle is the binary protocol of converting the python objects into bytes while encoding and then loading the bytes back into python objects while decoding.

##### Pickle Module: 
It is another way to serialize and deserialize Python objects. It serializes the Python object in a binary format, due to which it is not human-readable. It is faster and it also works with custom-defined objects. The Python pickle module is a better choice for serialization and deserialization of python objects. If you don’t need a human-readable format or if you need to serialize custom objects then it is recommended to use the pickle module.

In [4]:
# SERDE: SERIALIZATION DESERIALIZATION
# serialization of data: convert your object data into byte code and then store inside your system
# deserialization: conversion of byte code to object

from_file.to_pickle("pickle_basketball_data")

#### HDF5 is a data format that stores and manages large and complex data with lesser disk space and faster retrieve. 

While reading and working on large datasets, we often run into out of memory error because of the large memory used. Storing data is some other format which is fast to access and smaller in size, is one of the solutions for this problem. One such file format is HDF5. 


#### HDF stands for Hierarchical Data Format. Most common version used is Version 5. 

A HDF file can store any kind of heterogeneous data objects such as images, arrays, tables, graphs, documents etc. It organizes the data in hierarchical fashion. Every HDF file starts with a root group('/') that contains other groups and/or data objects.

In [5]:
# Create a h5 file which is another file format
# data in h5 is available in byte code. We need to deserialize data to see.

#Here we create a hdf file. h5_data is an instance of the file or object. We have not dumped any data yet.

h5_data = pd.HDFStore('h5_file.h5')

Here obj1 represents the key used to access the dataframe in HDF file. This key is useful because HDF file can store many data objects in the same file. Each data object can be accessed using the key.

In [6]:
# Storing data in hdf file
obj1 is a key and key is the identifier for the data object.
h5_data['obj1'] = from_file

C:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:3437: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block2_values] [items->Index(['Season', 'Tm', 'Lg', 'Pos'], dtype='object')]

  exec(code_obj, self.user_global_ns, self.user_ns)

In [7]:
# Though, these datasets are not at all readable from direct files.
h5_data['obj1']

,Unnamed: 0,Season,Age,Tm,Lg,Pos,G,MP,PER,TS%,...,Unnamed: 19,OWS,DWS,WS,WS/48,Unnamed: 24,OBPM,DBPM,BPM,VORP
0,0,2009-10,20.0,OKC,NBA,PF,6.0,153.0,15.3,0.596,...,NaN,0.2,0.3,0.5,0.144,NaN,-1.0,2.0,0.9,0.1
1,1,2010-11,21.0,OKC,NBA,PF,17.0,490.0,15.2,0.514,...,NaN,0.5,0.6,1.1,0.109,NaN,-1.6,0.8,-0.8,0.1
2,2,2011-12,22.0,OKC,NBA,PF,20.0,569.0,18.9,0.558,...,NaN,1.4,0.5,1.8,0.155,NaN,0.9,1.5,2.4,0.6
3,3,2012-13,23.0,OKC,NBA,PF,11.0,366.0,17.1,0.484,...,NaN,0.5,0.5,1.0,0.131,NaN,0.9,-0.1,0.8,0.3
4,4,2013-14,24.0,OKC,NBA,PF,17.0,581.0,16.6,0.633,...,NaN,1.0,0.7,1.7,0.143,NaN,1.1,1.7,2.8,0.7
5,5,2015-16,26.0,OKC,NBA,PF,18.0,602.0,15.3,0.629,...,NaN,1.4,0.7,2.0,0.163,NaN,2.1,1.5,3.6,0.9
6,6,2016-17,27.0,TOR,NBA,PF,10.0,307.0,14.4,0.527,...,NaN,0.0,0.4,0.4,0.065,NaN,-0.5,0.8,0.3,0.2
7,7,2017-18,28.0,TOR,NBA,PF,10.0,260.0,10.9,0.533,...,NaN,0.0,0.0,0.1,0.014,NaN,-1.7,-0.4,-2.2,0.0
8,8,2018-19,29.0,TOR,NBA,C,24.0,500.0,15.1,0.532,...,NaN,0.2,1.0,1.2,0.117,NaN,-1.6,1.2,-0.4,0.2
9,9,2019-20,30.0,TOR,NBA,C,11.0,251.0,25.2,0.702,...,NaN,0.8,0.5,1.3,0.250,NaN,5.2,2.6,7.7,0.6
10,10,2020-21,31.0,LAC,NBA,C,2.0,18.0,30.7,0.644,...,NaN,0.1,0.0,0.1,0.285,NaN,5.0,7.0,12.0,0.1
11,11,2021-22,32.0,MIL,NBA,PF,6.0,22.0,-3.9,0.267,...,NaN,-0.2,0.0,-0.2,-0.355,NaN,-13.4,-7.7,-21.0,-0.1
12,12,Career,NaN,NaN,NBA,NaN,152.0,4119.0,16.3,0.564,...,NaN,5.9,5.3,11.1,0.130,NaN,0.4,1.1,1.5,3.6
13,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,14,6 seasons,NaN,OKC,NBA,NaN,89.0,2761.0,16.5,0.567,...,NaN,5.0,3.2,8.2,0.142,NaN,0.7,1.2,1.9,2.7
15,15,4 seasons,NaN,TOR,NBA,NaN,55.0,1318.0,16.0,0.567,...,NaN,1.0,2.0,3.0,0.110,NaN,-0.1,1.0,1.0,1.0
16,16,1 season,NaN,MIL,NBA,NaN,6.0,22.0,-3.9,0.267,...,NaN,-0.2,0.0,-0.2,-0.355,NaN,-13.4,-7.7,-21.0,-0.1
17,17,1 season,NaN,LAC,NBA,NaN,2.0,18.0,30.7,0.644,...,NaN,0.1,0.0,0.1,0.285,NaN,5.0,7.0,12.0,0.1

In [8]:
# put data in hdf file
h5_data.put("obj2", from_file, format="table")

In [9]:
# Queries on h5 data: Here h5_data is serialized data. So, I am firing query on serialized data to get in readable format. 
# This is also called deserialization.
Writing: serialization, Reading: deserialization
h5_data.select("obj2", where = ["index >10 and index<15"])

,Unnamed: 0,Season,Age,Tm,Lg,Pos,G,MP,PER,TS%,...,Unnamed: 19,OWS,DWS,WS,WS/48,Unnamed: 24,OBPM,DBPM,BPM,VORP
11,11,2021-22,32.0,MIL,NBA,PF,6.0,22.0,-3.9,0.267,...,NaN,-0.2,0.0,-0.2,-0.355,NaN,-13.4,-7.7,-21.0,-0.1
12,12,Career,NaN,NaN,NBA,NaN,152.0,4119.0,16.3,0.564,...,NaN,5.9,5.3,11.1,0.130,NaN,0.4,1.1,1.5,3.6
13,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,14,6 seasons,NaN,OKC,NBA,NaN,89.0,2761.0,16.5,0.567,...,NaN,5.0,3.2,8.2,0.142,NaN,0.7,1.2,1.9,2.7

### OPERATIONS ON DATASET

In [6]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [7]:
type(df)

pandas.core.frame.DataFrame

In [8]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [9]:
df.dtypes  # the result is stored in the form of series. series are list kind of object in pandas library.

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [10]:
df.describe()  # by default it works only for column having numerical values

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [11]:
# We want to select only those columns which have datat type as object.
df.dtypes[df.dtypes == 'object']  
# series always store itself like list having index and corresponding data. So, here name, sex, ticket is index and 'object' is data.

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [12]:
df.dtypes[df.dtypes == 'object'].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [13]:
#If I pass this list in df then we get only those columns having data type as objects.
df1 = df[df.dtypes[df.dtypes == 'object'].index]
df1

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,211536,NaN,S
887,"Graham, Miss. Margaret Edith",female,112053,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,W./C. 6607,NaN,S
889,"Behr, Mr. Karl Howell",male,111369,C148,C
890,"Dooley, Mr. Patrick",male,370376,NaN,Q

In [15]:
# Description of categorical column
df1.describe()

                              Name   Sex  Ticket Cabin Embarked
count                          891   891     891   204      889
unique                         891     2     681   147        3
top     Isham, Miss. Ann Elizabeth  male  347082    G6        S
freq                             1   577       7     4      644

#### Lets filter out only those columns having data type as float.

In [16]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [17]:
df.dtypes[df.dtypes == 'float']

Age     float64
Fare    float64
dtype: object

In [18]:
df.dtypes[df.dtypes == 'float'].index

Index(['Age', 'Fare'], dtype='object')

In [19]:
#df[['Age','Fare']]
df[df.dtypes[df.dtypes == 'float'].index]

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [20]:
type(df['Name'])

pandas.core.series.Series

In [21]:
#If I want this in form of DataFrame, then we can enclose this inside a list.
df[['Name']]

                                                  Name
0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
..                                                 ...
886                              Montvila, Rev. Juozas
887                       Graham, Miss. Margaret Edith
888           Johnston, Miss. Catherine Helen "Carrie"
889                              Behr, Mr. Karl Howell
890                                Dooley, Mr. Patrick

[891 rows x 1 columns]

In [23]:
#Series is nothing but similar to list, so can perform the same operations on it to extract data.
#Lets extract data from 4th index to 10th index.
df['Name'][4:10]

4                             Allen, Mr. William Henry
5                                     Moran, Mr. James
6                              McCarthy, Mr. Timothy J
7                       Palsson, Master. Gosta Leonard
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                  Nasser, Mrs. Nicholas (Adele Achem)
Name: Name, dtype: object

In [24]:
df['Name'][4:16:2]

4                              Allen, Mr. William Henry
6                               McCarthy, Mr. Timothy J
8     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
10                      Sandstrom, Miss. Marguerite Rut
12                       Saundercock, Mr. William Henry
14                 Vestrom, Miss. Hulda Amanda Adolfina
Name: Name, dtype: object

In [25]:
df['Ticket'][5:16]

5        330877
6         17463
7        349909
8        347742
9        237736
10      PP 9549
11       113783
12    A/5. 2151
13       347082
14       350406
15       248706
Name: Ticket, dtype: object

In [26]:
#Let's try same thing on dataframe.
df[['Ticket']][5:16]

       Ticket
5      330877
6       17463
7      349909
8      347742
9      237736
10    PP 9549
11     113783
12  A/5. 2151
13     347082
14     350406
15     248706

In [27]:
#I want to sort my ticket dataset.
sorted(df['Ticket'])

['110152',
 '110152',
 '110152',
 '110413',
 '110413',
 '110413',
 '110465',
 '110465',
 '110564',
 '110813',
 '111240',
 '111320',
 '111361',
 '111361',
 '111369',
 '111426',
 '111427',
 '111428',
 '112050',
 '112052',
 '112053',
 '112058',
 '112059',
 '112277',
 '112379',
 '113028',
 '113043',
 '113050',
 '113051',
 '113055',
 '113056',
 '113059',
 '113501',
 '113503',
 '113505',
 '113505',
 '113509',
 '113510',
 '113514',
 '113572',
 '113572',
 '113760',
 '113760',
 '113760',
 '113760',
 '113767',
 '113773',
 '113776',
 '113776',
 '113781',
 '113781',
 '113781',
 '113781',
 '113783',
 '113784',
 '113786',
 '113787',
 '113788',
 '113789',
 '113789',
 '113792',
 '113794',
 '113796',
 '113798',
 '113798',
 '113800',
 '113803',
 '113803',
 '113804',
 '113806',
 '113806',
 '113807',
 '11668',
 '11668',
 '11751',
 '11751',
 '11752',
 '11753',
 '11755',
 '11765',
 '11767',
 '11767',
 '11769',
 '11771',
 '11774',
 '11813',
 '11967',
 '11967',
 '12233',
 '12460',
 '12749',
 '12749',
 '13049',
 '13213',
 '13214',
 '13502',
 '13502',
 '13502',
 '13507',
 '13507',
 '13509',
 '13567',
 '13568',
 '14311',
 '14312',
 '14313',
 '14973',
 '1601',
 '1601',
 '1601',
 '1601',
 '1601',
 '1601',
 '1601',
 '16966',
 '16966',
 '16988',
 '17421',
 '17421',
 '17421',
 '17421',
 '17453',
 '17453',
 '17463',
 '17464',
 '17465',
 '17466',
 '17474',
 '17474',
 '17764',
 '19877',
 '19877',
 '19928',
 '19928',
 '19943',
 '19943',
 '19947',
 '19950',
 '19950',
 '19950',
 '19950',
 '19952',
 '19972',
 '19988',
 '19996',
 '19996',
 '2003',
 '211536',
 '21440',
 '218629',
 '219533',
 '220367',
 '220845',
 '220845',
 '2223',
 '223596',
 '226593',
 '226875',
 '228414',
 '229236',
 '230080',
 '230080',
 '230080',
 '230136',
 '230136',
 '230433',
 '230433',
 '230434',
 '231919',
 '231919',
 '231945',
 '233639',
 '233866',
 '234360',
 '234604',
 '234686',
 '234818',
 '236171',
 '236852',
 '236853',
 '237442',
 '237565',
 '237668',
 '237671',
 '237736',
 '237736',
 '237789',
 '237798',
 '239853',
 '239853',
 '239853',
 '239854',
 '239855',
 '239856',
 '239865',
 '239865',
 '240929',
 '24160',
 '24160',
 '24160',
 '243847',
 '243847',
 '243880',
 '244252',
 '244252',
 '244270',
 '244278',
 '244310',
 '244358',
 '244361',
 '244367',
 '244367',
 '244373',
 '248698',
 '248706',
 '248723',
 '248727',
 '248727',
 '248727',
 '248731',
 '248733',
 '248738',
 '248738',
 '248740',
 '248747',
 '250643',
 '250644',
 '250644',
 '250646',
 '250647',
 '250647',
 '250648',
 '250649',
 '250649',
 '250651',
 '250652',
 '250653',
 '250655',
 '250655',
 '2620',
 '2623',
 '2624',
 '2625',
 '2626',
 '2627',
 '2627',
 '2628',
 '2629',
 '2631',
 '26360',
 '26360',
 '2641',
 '2647',
 '2648',
 '2649',
 '2650',
 '2651',
 '2651',
 '2653',
 '2653',
 '2659',
 '2659',
 '2661',
 '2661',
 '2662',
 '2663',
 '2664',
 '2665',
 '2665',
 '2666',
 '2666',
 '2666',
 '2666',
 '2667',
 '2668',
 '2668',
 '2669',
 '26707',
 '2671',
 '2672',
 '2674',
 '2677',
 '2678',
 '2678',
 '2680',
 '2683',
 '2685',
 '2686',
 '2687',
 '2689',
 '2690',
 '2691',
 '2691',
 '2693',
 '2694',
 '2695',
 '2697',
 '2699',
 '2699',
 '2700',
 '27042',
 '27267',
 '27849',
 '28134',
 '28206',
 '28213',
 '28220',
 '28228',
 '28403',
 '28403',
 '28424',
 '28425',
 '28551',
 '28664',
 '28665',
 '29011',
 '2908',
 '2908',
 '29103',
 '29104',
 '29105',
 '29106',
 '29106',
 '29106',
 '29108',
 '2926',
 '29750',
 '29750',
 '29751',
 '3101264',
 '3101265',
 '3101267',
 '3101276',
 '3101277',
 '3101278',
 '3101278',
 '3101281',
 '3101295',
 '3101295',
 '3101295',
 '3101295',
 '3101295',
 '3101295',
 '3101296',
 '3101298',
 '31027',
 '31027',
 '31028',
 '312991',
 '312992',
 '312993',
 '31418',
 '315037',
 '315082',
 '315084',
 '315086',
 '315088',
 '315089',
 '315090',
 '315093',
 '315094',
 '315096',
 '315097',
 '315098',
 '315151',
 '315153',
 '323592',
 '323951',
 '324669',
 '330877',
 '330909',
 '330919',
 '330923',
 '330931',
 '330932',
 '330935',
 '330958',
 '330959',
 '330979',
 '330980',
 '334912',
 '335097',
 '335677',
 '33638',
 '336439',
 '3411',
 '341826',
 '34218',
 '342826',
 '343095',
 '343120',
 '343275',
 '343276',
 '345364',
 '345572',
 '345763',
 '345764',
 '345764',
 '345765',
 '345767',
 '345769',
 '345770',
 '345773',
 '345773',
 '345773',
 '345774',
 '345777',
 '345778',
 '345779',
 '345780',
 '345781',
 '345783',
 '3460',
 '347054',
 '347054',
 '347060',
 '347061',
 '347062',
 '347063',
 '347064',
 '347067',
 '347068',
 '347069',
 '347071',
 '347073',
 '347074',
 '347076',
 '347077',
 '347077',
 '347077',
 '347077',
 '347078',
 '347080',
 '347080',
 '347081',
 '347082',
 '347082',
 '347082',
 '347082',
 '347082',
 '347082',
 '347082',
 '347083',
 '347085',
 '347087',
 '347088',
 '347088',
 '347088',
 '347088',
 '347088',
 '347088',
 '347089',
 '3474',
 '347464',
 '347466',
 '347468',
 '347470',
 '347742',
 '347742',
 '347742',
 '347743',
 '348121',
 '348123',
 '348124',
 '349201',
 '349203',
 '349204',
 '349205',
 '349206',
 '349207',
 '349208',
 '349209',
 '349210',
 '349212',
 '349213',
 '349214',
 '349215',
 '349216',
 '349217',
 '349218',
 '349219',
 '349221',
 '349222',
 '349223',
 '349224',
 '349225',
 '349227',
 '349228',
 '349231',
 '349233',
 '349234',
 '349236',
 '349237',
 '349237',
 '349239',
 '349240',
 '349241',
 '349242',
 '349243',
 '349244',
 '349245',
 '349246',
 '349247',
 '349248',
 '349249',
 '349251',
 '349252',
 '349253',
 '349254',
 '349256',
 '349257',
 '349909',
 '349909',
 '349909',
 '349909',
 '349910',
 '349912',
 '350025',
 '350026',
 '350029',
 '350034',
 '350035',
 '350036',
 '350042',
 '350043',
 '350046',
 '350047',
 '350048',
 '350050',
 '350052',
 '350060',
 '350404',
 '350406',
 '350407',
 '350417',
 '35273',
 '35273',
 '35273',
 '35281',
 '35281',
 '35851',
 '35852',
 '358585',
 '358585',
 '36209',
 '362316',
 '363291',
 '363291',
 '363291',
 '363294',
 '363592',
 '364498',
 '364499',
 '364500',
 '364506',
 '364511',
 '364512',
 '364516',
 '364516',
 '364846',
 '364848',
 '364849',
 '364849',
 '364850',
 '364851',
 '365222',
 '365226',
 '36568',
 '367226',
 '367226',
 '367228',
 '367229',
 '367230',
 '367230',
 '367231',
 '367232',
 '367655',
 '368323',
 '36864',
 '36865',
 '36866',
 '368703',
 '36928',
 '36928',
 '36947',
 '36947',
 '36963',
 '36967',
 '36973',
 '36973',
 '370129',
 '370129',
 '370365',
 '370365',
 '370369',
 '370370',
 '370371',
 '370372',
 '370373',
 '370375',
 '370376',
 '370377',
 '371060',
 '371110',
 '371110',
 '371110',
 '371362',
 '372622',
 '373450',
 '374746',
 '374887',
 '374910',
 '376564',
 '376564',
 '376566',
 '382649',
 '382651',
 '382652',
 '382652',
 '382652',
 '382652',
 '382652',
 '383121',
 '384461',
 '386525',
 '392091',
 '392092',
 '392096',
 '392096',
 '394140',
 '4133',
 '4133',
 '4133',
 '4133',
 '4134',
 '4135',
 '4136',
 '4137',
 '4138',
 '4579',
 '54636',
 '54636',
 '5727',
 '65303',
 '65304',
 '65306',
 '6563',
 '693',
 '695',
 '7267',
 '7534',
 '7534',
 '7540',
 '7545',
 '7546',
 '7552',
 '7553',
 '7598',
 '8471',
 '8475',
 '9234',
 'A./5. 2152',
 'A./5. 3235',
 'A.5. 11206',
 'A.5. 18509',
 'A/4 45380',
 'A/4 48871',
 'A/4 48871',
 'A/4. 20589',
 'A/4. 34244',
 'A/4. 39886',
 'A/5 21171',
 'A/5 21172',
 'A/5 21173',
 'A/5 21174',
 'A/5 2466',
 'A/5 2817',
 'A/5 3536',
 'A/5 3540',
 'A/5 3594',
 'A/5 3902',
 'A/5. 10482',
 'A/5. 13032',
 'A/5. 2151',
 'A/5. 3336',
 'A/5. 3336',
 'A/5. 3337',
 'A/5. 851',
 'A/S 2816',
 'A4. 54510',
 'C 17369',
 'C 4001',
 'C 7075',
 'C 7076',
 'C 7077',
 'C.A. 17248',
 'C.A. 18723',
 'C.A. 2315',
 'C.A. 2315',
 'C.A. 24579',
 'C.A. 24580',
 'C.A. 2673',
 'C.A. 2673',
 'C.A. 29178',
 'C.A. 29395',
 'C.A. 29566',
 'C.A. 31026',
 'C.A. 31921',
 'C.A. 31921',
 'C.A. 31921',
 'C.A. 33111',
 'C.A. 33112',
 'C.A. 33112',
 'C.A. 33595',
 'C.A. 34260',
 'C.A. 34651',
 'C.A. 34651',
 'C.A. 34651',
 'C.A. 37671',
 'C.A. 37671',
 'C.A. 5547',
 'C.A. 6212',
 'C.A./SOTON 34068',
 'CA 2144',
 'CA 2144',
 'CA 2144',
 'CA 2144',
 'CA 2144',
 'CA 2144',
 'CA. 2314',
 'CA. 2343',
 'CA. 2343',
 'CA. 2343',
 'CA. 2343',
 'CA. 2343',
 'CA. 2343',
 'CA. 2343',
 'F.C. 12750',
 'F.C.C. 13528',
 'F.C.C. 13529',
 'F.C.C. 13529',
 'F.C.C. 13529',
 'F.C.C. 13531',
 'Fa 265302',
 'LINE',
 'LINE',
 'LINE',
 'LINE',
 'P/PP 3381',
 'P/PP 3381',
 'PC 17318',
 'PC 17473',
 'PC 17474',
 'PC 17475',
 'PC 17476',
 'PC 17477',
 'PC 17477',
 'PC 17482',
 'PC 17483',
 'PC 17485',
 'PC 17485',
 'PC 17558',
 'PC 17558',
 'PC 17569',
 'PC 17569',
 'PC 17572',
 'PC 17572',
 'PC 17572',
 'PC 17582',
 'PC 17582',
 'PC 17582',
 'PC 17585',
 'PC 17590',
 'PC 17592',
 'PC 17593',
 'PC 17593',
 'PC 17595',
 'PC 17596',
 'PC 17597',
 'PC 17599',
 'PC 17600',
 'PC 17601',
 'PC 17603',
 'PC 17604',
 'PC 17604',
 'PC 17605',
 'PC 17608',
 'PC 17608',
 'PC 17609',
 'PC 17610',
 'PC 17611',
 'PC 17611',
 'PC 17612',
 'PC 17754',
 'PC 17755',
 'PC 17755',
 'PC 17755',
 'PC 17756',
 'PC 17757',
 'PC 17757',
 'PC 17757',
 'PC 17757',
 'PC 17758',
 'PC 17758',
 'PC 17759',
 'PC 17760',
 'PC 17760',
 'PC 17760',
 'PC 17761',
 'PC 17761',
 'PP 4348',
 'PP 9549',
 'PP 9549',
 'S.C./A.4. 23567',
 'S.C./PARIS 2079',
 'S.C./PARIS 2079',
 'S.O./P.P. 3',
 'S.O./P.P. 3',
 'S.O./P.P. 751',
 'S.O.C. 14879',
 'S.O.C. 14879',
 'S.O.C. 14879',
 'S.O.C. 14879',
 'S.O.C. 14879',
 'S.O.P. 1166',
 'S.P. 3464',
 'S.W./PP 752',
 'SC 1748',
 'SC/AH 29037',
 'SC/AH 3085',
 'SC/AH Basle 541',
 'SC/PARIS 2131',
 'SC/PARIS 2133',
 'SC/PARIS 2146',
 'SC/PARIS 2149',
 'SC/PARIS 2167',
 'SC/Paris 2123',
 'SC/Paris 2123',
 'SC/Paris 2123',
 'SC/Paris 2163',
 'SCO/W 1585',
 'SO/C 14885',
 'SOTON/O.Q. 3101305',
 'SOTON/O.Q. 3101306',
 'SOTON/O.Q. 3101307',
 'SOTON/O.Q. 3101310',
 'SOTON/O.Q. 3101311',
 'SOTON/O.Q. 3101312',
 'SOTON/O.Q. 392078',
 'SOTON/O.Q. 392087',
 'SOTON/O2 3101272',
 'SOTON/O2 3101287',
 'SOTON/OQ 3101316',
 'SOTON/OQ 3101317',
 'SOTON/OQ 392076',
 'SOTON/OQ 392082',
 'SOTON/OQ 392086',
 'SOTON/OQ 392089',
 'SOTON/OQ 392090',
 'STON/O 2. 3101269',
 'STON/O 2. 3101273',
 'STON/O 2. 3101274',
 'STON/O 2. 3101275',
 'STON/O 2. 3101280',
 'STON/O 2. 3101285',
 'STON/O 2. 3101286',
 'STON/O 2. 3101288',
 'STON/O 2. 3101289',
 'STON/O 2. 3101292',
 'STON/O 2. 3101293',
 'STON/O 2. 3101294',
 'STON/O2. 3101271',
 'STON/O2. 3101279',
 'STON/O2. 3101279',
 'STON/O2. 3101282',
 'STON/O2. 3101283',
 'STON/O2. 3101290',
 'SW/PP 751',
 'W./C. 14258',
 'W./C. 14263',
 'W./C. 6607',
 'W./C. 6607',
 'W./C. 6608',
 'W./C. 6608',
 'W./C. 6608',
 'W./C. 6608',
 'W./C. 6609',
 'W.E.P. 5734',
 'W/C 14208',
 'WE/P 5735',
 'WE/P 5735']

In [28]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [29]:
for i in df.columns:
    print(df[i])

0        1
1        2
2        3
3        4
4        5
      ...
886    887
887    888
888    889
889    890
890    891
Name: PassengerId, Length: 891, dtype: int64
0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64
0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64
0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object
0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: object
0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64
0      1
1      1
2      0
3      1
4      0
      ..
886    0
887    0
888    1
889    0
890    0
Name: SibSp, Length: 891, dtype: int64
0      0
1      0
2      0
3      0
4      0
      ..
886    0
887    0
888    2
889    0
890    0
Name: Parch, Length: 891, dtype: int64
0             A/5 21171
1              PC 17599
2      STON/O2. 3101282
3                113803
4                373450
             ...
886              211536
887              112053
888          W./C. 6607
889              111369
890              370376
Name: Ticket, Length: 891, dtype: object
0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64
0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ...
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: Cabin, Length: 891, dtype: object
0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [30]:
# I want to add a new column in my data frame.
df['mohd'] = 'irfan'

In [5]:
df

NameError: name 'df' is not defined

In [32]:
#I want to store all data in passenger id  column into my mohd column.
df['mohd'] = df['PassengerId']

In [33]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,mohd
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,887
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,888
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,889
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,890
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,891

In [34]:
df['Cabin']

0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ...
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: Cabin, Length: 891, dtype: object

In [35]:
pd.Categorical(df['Cabin'])  # gives the data, lenght and distinct categories it has.

[NaN, 'C85', NaN, 'C123', NaN, ..., NaN, 'B42', NaN, 'C148', NaN]
Length: 891
Categories (147, object): ['A10', 'A14', 'A16', 'A19', ..., 'F38', 'F4', 'G6', 'T']

In [36]:
pd.Categorical(df['Pclass'])

[3, 1, 3, 1, 3, ..., 2, 1, 3, 1, 3]
Length: 891
Categories (3, int64): [1, 2, 3]

In [37]:
df['Pclass'].unique()    # unique data in the column Pclass.

array([3, 1, 2], dtype=int64)

In [38]:
df['Cabin'].isnull()   # wherever there is null value, it gives us True otherwise False.

0       True
1      False
2       True
3      False
4       True
       ...
886     True
887    False
888     True
889    False
890     True
Name: Cabin, Length: 891, dtype: bool

In [39]:
df['Cabin'][df['Cabin'].isnull() == False]  # returns all values which are not null.

1              C85
3             C123
6              E46
10              G6
11            C103
          ...
871            D35
872    B51 B53 B55
879            C50
887            B42
889           C148
Name: Cabin, Length: 204, dtype: object

In [40]:
#I want to extract row indexes wherever there is no value or isnull == True.
#Since above data is in form of series which is same as list. We can perform list operations.
ser = df['Cabin'][df['Cabin'].isnull()]
ser.index

Int64Index([  0,   2,   4,   5,   7,   8,   9,  12,  13,  14,
            ...
            878, 880, 881, 882, 883, 884, 885, 886, 888, 890],
           dtype='int64', length=687)

In [41]:
#Let's extract information row wise.
df.iloc[ser.index]   # we get the row-wise dataset by providing the indexes.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,mohd
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,5
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,6
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S,885
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q,886
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,887
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,889
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,891

In [42]:
# I can give my arbitrary rows against which I eant data.
df.iloc[[1,3,5,9]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,mohd
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,6
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,10

Find the names of passengers who have given the maximum fare.

In [32]:
l=[]
for i in range(len(df['Fare'])):
    l.append(df['Fare'][i])
from functools import reduce
#l=[1,3,5,6,78,9,34,56,69]
print(reduce(lambda x,y:max(x,y), l))

512.3292

In [31]:
n = []
for i in range(len(df['Fare'])):
    if df['Fare'][i] == 512.3292:
        n.append(i)
df.iloc[n]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C

In [34]:
#Method-2
max_fare = df['Fare'] == max(df['Fare'])   # gives true wherever the fare is maximum in entire column

In [35]:
df[max_fare]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C

In [36]:
df[max_fare]['Name']

258                      Ward, Miss. Anna
679    Cardeza, Mr. Thomas Drake Martinez
737                Lesurer, Mr. Gustave J
Name: Name, dtype: object

In [37]:
#Combine two columns: PassengerId and Age into a new column
df['new_col'] = df['PassengerId'] + df['Age']
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,23.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,40.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,29.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,39.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,914.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,907.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,916.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,923.0

tsv: tab seperated value

In [39]:
#pd.read_table("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv")
pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep='\t')

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

https://raw.githubusercontent.com/justmarkham/DAT8/master/data/beer.txt
https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/US_Crime_Rates/US_Crime_Rates_1960_2014.csv
https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/datasets.csv
https://drive.google.com/file/d/1etGP85wJWsgqbsh3gX5oxc8dPKLMA1eT/view